### ISSUE TITLE
Bug/Feature: "peeking" lyrics from next is broken, but I think there's a better way...

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#1090]
A recent change stopped the _lyrics peeking_ thing,  where when playing patter without a cuesheet if the next song in the playlist was a singer it showed that song’s cuesheet.

The problem was that the code in loadCuesheets that handled that case used variable currentSongType and this used to be set before loadCuesheets was called, but is now called after it.  (So it only worked if you selected another patter then select the right patter song!)

The fix is simply to move the setting of loadCuesheets inMainWindow::loadMP3File to before the call to loadCuesheets.

However, this doesn’t help those using Dark Mode:  even if the playlist has both patter and singer selectedSOngRow returns -1 so nextVisibleSongRow returns -1 so it thinks there is no next song in the list.

_I think there is a better solution._  In SquareView you could select a song from the singers list, show the cuesheet,  then if you played a song from the patters list it did not change the cuesheet, it was still visible.

SquareDesk could do this.  Suppose if a patter was played and there was no sequence sheet found, it did nothing -- it didn’t change what the cuesheet tab would show.

Advantage:
You could select any “singer” song and get the cuesheet ready then play any patter song.  This would work in either mode, and is more flexible than the current light-mode.   

Disadvantage:
You lose the ability to have a dummy sequence sheet shown for a patter with no known sequence.
Assuming this is used,  I doubt it is ever required at a dance, just at home, so perhaps if there was no previous singer selected (so nothing in the cuesheet tab) it could do the “We couldn't find any sequence sheets that match this song.” thing?   Restart SquareDesk and select the patter song and you see this dummy sequence sheet.

**Comment by mpogue2** [comment]
Indeed I am really missing the "peek" feature, which got broken somewhere along the way.  I tried to debug it once before, but I got lost in figuring out what was wrong.  I think you've now pinpointed the problem, which really helps!

I am in favor of getting rid of the "cuesheets for patter" idea.  I don't think anybody uses it, and as you suggest, there are better alternatives.

I really liked the way that "peek" worked, because it did NOT require that the user load the singer first.  So, it did not force me to have to remember to load the singer before every patter.  Is there a way that we could retain the "no prior action required" feature, while still doing it your suggested way?

I'm not 100% sure how to do this.  Maybe:
- in Dark Mode, if a patter is loaded from a playlist (vs loaded from the songTable), then the cuesheet loaded is taken from the next item in the playlist, IF that is a singer.  If not a singer, or if not loaded from a playlist, then "retain previous cuesheet".
- in Light Mode, there is little distinction between "loaded from a playlist" and "loaded from the songTable".  If a song is in a playlist in Light Mode, it is both.  In Light Mode, we could just NOT overwrite the cuesheet, if a patter is loaded, thereby retaining the "last cuesheet loaded".  I think that's what you're suggesting.

This is diverging the Light and Dark Mode behaviors, which I am 100% OK with right now.  Note, however, that my intent is to eventually create a New Light Mode that is based on the Dark Mode code, and to obsolete (and delete) the current Light Mode mechanism.  I don't think we're ready for this yet, though.  Too many things still need to be fixed in Dark Mode.

**Comment by sharmanr** [comment]
I’ve found recently, because of low numbers and other reasons, I’ve had to decide on the fly when to do singers.  Calling while dancing a patter is fine but not for a singer (for me).  So when I thought “ok we have two squares now so I can do a patter and a singer” I altered the playlist (light mode) to have the patter before the singer only to find the “peek” no longer worked!  That’s why I thought my way was more flexible since I would be able just click on the singer,  get the lyrics and play a patter without having to alter the playlist.   You are clearly more organized(!) and so for you it’s easier to have the playlist setup and use the peek.

I think your suggestion does allow both ways:  we try peeking first and if there’s a singer use it,  otherwise do nothing and if there was a cuesheet loaded we use it.

**Comment by sharmanr** [comment]
Please try new branch peekrevised
New algorithm:
New variable cueSheetLoaded is initialzed to false, and is set to true when any cuesheet is loaded.
When playing a patter song that does not have a cuesheet for it:
  if (in light mode and there is a song after it and this is a singer that has a cuesheet)
  or (in dark mode and a song was selected from one of the 3 playlists
      and there is a song after it in this playlist
      and this song is a singer)
  then
      try and load that singer’s playlist
  else
      if cueSheetLoaded
      then
         do nothing else, so the previous cuesheet is still visible
      else
         (as before)
         display the “We couldn't find any sequence sheets that match this song” message
	 (which doesn’t actually work because you can’t save this, but that’s another bug...)

**Comment by sharmanr** [comment]
I need to modify SquareDesk-DEV/test123/test123.pro because my Xcode is behind yours.  I tried to have git ignore this change by adding to .git/info/exclude.  I have *~ and TAGS there and they work, but putting test123.pro or SquareDesk-DEV/test123/test123.pro doesn't work,  a git status keeps showing the file so I have to move it away before doing the commit and moving it back.   Is there some trick I'm missing?

**Comment by sharmanr** [comment]
I tried seeing what happens if you do actually attempt to write patter cuesheets using the "We couldn't find any..." scenario.  I can edit but (a) in Light mode there is no Save As button,  (b) in Dark mode the Save and Save as menu entries are greyed out.   Is it worth fixing this or rip out that part?

**Comment by sharmanr** [comment]
I have to modify test123.pro because my xcode is different from yours.  In .git/info/exclude I have *~ and TAGS and those work, but when I try putting either test123.pro or SquareDesk-DEV/test123/test123.pro in there it still shows up on a git status.  (So I have to move it out the way and restore github version before a commit.)   Is there some trick I'm missing ?

**Comment by sharmanr** [comment]
The Cuesheet "Save as" menu item is now enabled when the patter.template.html is being edited.  

The intent is as long as no lyrics or cuesheets are loaded, then when a patter doesn't have a following singer (so the "peek thing" works) one can add cuesheets to a patter.  As soon as a real cuesheet is loaded this behaviour stops,  cuesheets remain.   When editing the patter.template.html, though, the "Save as" re-loads the cuesheet which set cueSheetLoaded true so it could only be done once.   To prevent this, the "Save as" action saves and restores the value of cueSheetLoaded around the call to saveLyricsAs.

This is 91c38d63361fc6b196e3cb86b4aa99e43f734f4e

**Comment by mpogue2** [comment]
@sharmanr Sorry it took me so long to review your changes!  I've been out of town....

I really really like what you've done with the new PEEK.  I so need peek while I am calling, and it didn't "just work" for me.
With your changes, "it just works"!  So, I say let's merge this in! :-)

There are only two more things to think about:

1. one that doesn't match your comment in the commit:
- when I have previously loaded a singing call (in Dark Mode), AND when I double-click (IN THE MAIN SONG TABLE) to load patter that does not have a cuesheet, by your commit comment I should get the patter template, but I don't, the previous cuesheet remains.  So, once I have a cuesheet loaded in dark mode, there doesn't seem to be any way to get to the patter template.
- If I quite SquareDesk, come back in (DARK MODE), and double-click in a playlist to load the last patter in a playlist (with no singer after it), I *do* see the patter template.  But, once I get a singing call loaded, I don't think I can ever see the patter template again.

Now, I think you bring up a good question, which boils down to "do we really need the patter template?". Which brings up the question: "do we really need the singing call template either?".  I think the answer should be "no, let's rip them out entirely, and replace with a new menu item : Cuesheet > New > {list names of *.template.html files}.   This gives us a couple of things:  
- any number of templates (e.g. 1-column vs 2-column, singer vs patter)
- we don't have to detect when a song doesn't have a cuesheet, just don't populate the pulldown menu, and show nothing for a cuesheet (or maybe a generic "no cuesheet found").

I think this would be simpler.  Personally, I always make new cuesheets from existing cuesheets anyway.  I never use the templates.

2. And, the second thing is that when we are peeking at a cuesheet, patter is playing, cuesheet is from the next singer after, there is still a menu item:  Cuesheet > Auto-scroll Patter that is checked.  I was thinking that maybe we should un-check it, and then restore when we go back to a singer.  But, this save/restore seems to be pretty fragile and error-prone to me.  I think it might be better (since nobody uses scrolled patter cuesheets anyway) to just do this:  If patter is loaded, hide the Cuesheet > Auto-scroll Patter menu item (it's already disabled for patter I believe, even though it might be checked), OR replace it with a greyed-out un-checked menu item called "auto-scroll OFF" ELSE unhide it.

I love the peek feature!  What do you think about the above two other questions?

**Comment by sharmanr** [comment]
Thanks.  Regarding 1, perhaps my comment was not clear, but I did say "As soon as a real cuesheet is loaded this behaviour stops, cuesheets remain."  The idea was that this editing of template cuesheets was not something normally done. certainly not at a dance, only in practise mode.  So it works for a while as long as no real cuesheet is loaded.  Then cuesheets remain (persist).   Which is what you observed, but perhaps I didn't explain properly.

For the other questions I'd have to think about it for a while.   

Can I do git pull do submit the  peekrevised branch to the main one?   We can then look at patter templates.   I also want to make a branch for changes to right button and keystrokes in light mode.

**Comment by mpogue2** [comment]
OK, I messed the whole git tree trying to put in a different bug fix, and since your branch is much better than what we have, I went ahead and merged it in.... I hope you're OK with that!

I understand your comment better now!  I'm not sure that this kind of modal behavior would be expected by an ordinary user, but let's commit what you have (well, that's already done now! :-), and let's actually use it, before we decide whether any more changes are needed.  I think it works WAY WAY better than what we had!  Maybe we can make it even better, but maybe it's now Totally Good Enough! :-)

Could you check the top-of-tree and make sure that it works the way you designed it?  Thanks!

**Comment by sharmanr** [comment]
Yes I checked out 91c38d63 and it works as I expected.

**Comment by mpogue2** [comment]
Awesome!  So, let's live with it for a while, and see what we think!  Thanks so much for this change -- I LOVE PEEK :-)

**Comment by sharmanr** [comment]
Thanks Mike!
