### ISSUE TITLE
Bug?: Packaging scripts require a non-default pathname for build directories

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#1154]
From @sharmanr:
 
It seems that the build directory was renamed from `build-SquareDesk-Qt_*_for_macOS-*` to `build/Qt_*_for_macOS-*`.

I made the following change (to the copy in the build directory) and it worked:

```
richard@minnie test123 % diff ../../../test123/PackageIt_M1.command  .
18c18
<      */build-SquareDesk-Qt_*_for_macOS-* )
---
>      */build/Qt_*_for_macOS-* )
```

My comments on this:

All the build directories I have on my systems are of this form:

![image](https://github.com/user-attachments/assets/e535061e-683a-4260-80ff-b925f6a71844)

BUT, I do think I HAD the same problem that you are describing, when I moved to 6.7.2. 
When a new Qt release comes out, and a new Build & Run "kit" is setup, the default build directory doesn't match the above. 
I think I might have I been just manually changing this for every Qt release? :-)

I remember I did have to change the pathnames in the Kit to look like this:

![image](https://github.com/user-attachments/assets/297cf5f4-2e5f-494b-916b-25a509d52f2e)

But, maybe we should just move everything to the default folder, so that this manual Kit setup editing doesn't have to be done anymore?

BTW, the same pathname question applies to `PackageIt.command L20` (the X86 packaging script).

What do you think?  Change the default, and make the PackageIt files match the default?
(I'd want to double check that the default really is `<rootdir>/build/Qt.*` -- I no longer remember how precisely it figured out the rootDir...)

Or, maybe should we just modify the PackageIt files to look for something far more general, like

    `*/*Qt_*_for_MacOS-*`

and leave the whole question of EXACTLY which subfolder the build is in completely out of this test?

What do you think?  Multiple options here....

**Comment by mpogue2** [comment]
I guess the root of the problem here is that we don't have a way to check in the parameters that go into the QtCreator Kit, namely those pathnames in the screen capture above.  But, these are absolute pathnames, so even if we could, everybody would have to do their file hierarchy exactly like I do (which was not my intent).

So, do we 
- standardize the location of the builds, or do we 
- modify the Package* scripts to work with any build directory location, or do we 
- just eliminate that check entirely?  

I did put this check in there intentionally, because I ran it in the wrong directory at some point in the past, and that was hard to debug...but maybe because the PackageIt command files are now COPIED to the build output directories, this problem really won't occur again, and it's OK to delete this check entirely?

**Comment by sharmanr** [comment]
Hi Mike.

I assumed that you had specifically renamed the build directory structure.  I did update Qt recently because it wouldn’t build for me with my previous Qt.  Now, unlike before, I have a build directory with subdirectories Qt_6_7_2_for_macOS-Debug and Python_from_Path-Debug.  I have no idea what the Python one is.

I would NOT suggest eliminating the check because there are 3 copies of PackageIt_M1.command in the tree (one in test123, one in build/Qt* and one in Qt/Python* .

When I remove SquareDesk.pro.user and then open SquareDesk.pro to start from scratch it shows

￼

I don’t know why Debug occurs twice.  I left everything as the default.

I suggest we want to basically check that we are executing the Package* command from the build-mac os directory,  so check that the current directory name contains the regexp “build.*macOS” .    So rather than the CASE with a glob where I think the / won’t match the * , we use a simple regexp.

Also,  rather than doing the “cd ..” and then checking the directory is ok,  stay where we are and that way check we are in a test123 directory (and not below it).

I created a simple file ~/tmp/check and tested it,  I think it’s ok.

#! /bin/sh
echo checking $PWD
echo $PWD | grep -E -q 'build.*Qt.*macOS-(Debug|Release)/test123$' || { echo invalid directory ; exit 1; }
echo ok


***@***.*** test123 % check() { ~/tmp/check; }
***@***.*** test123 % check
checking /Users/richard/tmp/build-SquareDesk-Qt_6_5_3_for_macOS-Debug/test123
ok
***@***.*** test123 % cd ..
***@***.*** build-SquareDesk-Qt_6_5_3_for_macOS-Debug % check
checking /Users/richard/tmp/build-SquareDesk-Qt_6_5_3_for_macOS-Debug
invalid directory
***@***.*** build-SquareDesk-Qt_6_5_3_for_macOS-Debug % mkdir test123/silly
***@***.*** build-SquareDesk-Qt_6_5_3_for_macOS-Debug % cd test123/silly
***@***.*** silly % check
checking /Users/richard/tmp/build-SquareDesk-Qt_6_5_3_for_macOS-Debug/test123/silly
invalid directory
***@***.*** silly % cd ~/GitHub/SquareDesk/SquareDesk-DEV/build/Qt_6_7_2_for_macOS-Debug/test123
***@***.*** test123 % check
checking /Users/richard/GitHub/SquareDesk/SquareDesk-DEV/build/Qt_6_7_2_for_macOS-Debug/test123
ok
***@***.*** test123 % cd ..
***@***.*** Qt_6_7_2_for_macOS-Debug % check
checking /Users/richard/GitHub/SquareDesk/SquareDesk-DEV/build/Qt_6_7_2_for_macOS-Debug
invalid directory
***@***.*** Qt_6_7_2_for_macOS-Debug % cd ~/GitHub/SquareDesk/SquareDesk-DEV/build/Python_from_Path-Debug/test123/
<areDesk/SquareDesk-DEV/build/Python_from_Path-Debug/test123/
***@***.*** test123 % check
checking /Users/richard/GitHub/SquareDesk/SquareDesk-DEV/build/Python_from_Path-Debug/test123
invalid directory
***@***.*** test123 %

**Comment by mpogue2** [comment]
Sounds good to me...if you're around do you want to do this now?
I'm about ready to create a V1.0.10 test build for Paul B to test (with a bunch of changes he's waiting for)...

**Comment by mpogue2** [comment]
BTW, I think there should be at least 2 copies of the PackageIt scripts.  

One is the source file, in test123 (sorry for that name, that was the very first folder I created just to test Qt, and the build grew organically from there, and now we're stuck with it... :-) :-).  The other is a COPY of that file that I stick into the build directory at build time.  Then, double-clicking on that file in a build directory will package THAT build.  I also don't know what the python directory is, QtCreator now supports Python, too, but I don't use it.

**Comment by sharmanr** [comment]
Ok, can do.   I’m trying it now…


Should I create a stream and do that?  Or do it in the main stream?   Or chicken out and send you the file after I’ve checked it?

**Comment by sharmanr** [comment]
I hate to admit it, but i didn’t realize you could double-click on it!  I had a script that went there and execute it…

**Comment by mpogue2** [comment]
Ah, just push to Master, and I'll test it here (right after I checkin the 1.0.10 version number changes...)

**Comment by sharmanr** [comment]
Ok,  done.  2 files changed.

**Comment by mpogue2** [comment]
I think you still need to push it.  I don't see the changes here.

**Comment by sharmanr** [comment]
Oh?  I think I did a git push in the shell (but don’t have it now) but in GitHub Desktop it seemed like it hadn’t worked, so did a Push there.
GitHub Desktop shows

￼


GitCraken shows this:


￼


And yet, when I bring up the shell I see this:


***@***.*** SquareDesk % git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	SquareDesk-DEV/build/

nothing added to commit but untracked files present (use "git add" to track)
***@***.*** SquareDesk % 

Ok, I’ll try a push again…

**Comment by mpogue2** [comment]
Ah, I can see it now!  I don't know what you did...

**Comment by sharmanr** [comment]
Oh,  OK, found a different way to push…    I find this github quite confusing!   I tried a git push from the command line but got this error
***@***.*** SquareDesk % git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	SquareDesk-DEV/build/

nothing added to commit but untracked files present (use "git add" to track)
***@***.*** SquareDesk %


Anyway,  I think it’s there now…   When I look with a browser I see the commit.

**Comment by mpogue2** [comment]
I use GitKraken....SO nice to view what's happening visually! :-)

**Comment by mpogue2** [comment]
Trying out your changes now!

**Comment by sharmanr** [comment]
The problem with GUIs is there’s no record!    So what I think I did and what I actually did might be different!

Anyway, it’s ok now?

**Comment by sharmanr** [comment]
I often use that to see but forget how to use it for changes.

**Comment by mpogue2** [comment]
Yes, ALL IS WELL.  Script worked (I got some errors, but I think they are bogus from the deploy step), and I'm gonna check in the version number changes, and will hand a version to Paul B to start testing!

Thanks for doing this in REAL TIME! :-)

**Comment by sharmanr** [comment]
Thanks.  I should try that with some test project.

**Comment by sharmanr** [comment]
Great!   Time for bed, then;  I have Don Beck’s mental image practise Zoom session at 8.

**Comment by sharmanr** [comment]
I did a git pull just now and a git status showed an untracked file “../build/“.   I deleted it and reconfigured project and Qt re-created it.  No problem.

However,  the build fails:

cd test123/ && /Users/richard/Qt/6.7.2/macos/bin/qmake6 -o Makefile /Users/richard/GitHub/SquareDesk/SquareDesk-DEV/test123/test123.pro -qtconf /Users/richard/Qt/6.7.2/ios/bin/target_qt.conf -spec macx-ios-clang CONFIG+=debug CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug
Project ERROR: Unknown module(s) in QT: webenginewidgets
make: *** [sub-test123-qmake_all] Error 3
07:34:24: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project SquareDesk (kit: Qt 6.7.2 for iOS)
The kit Qt 6.7.2 for iOS has configuration issues which might be the root cause for this problem.
When executing step "qmake"

When I run QtMaintainer, I see QT Webengine but only for Qt 6.8.0-beta2, whearas the rest of the selected components are 6.7.2.

What should I do?
Thanks,
Richard

**Comment by mpogue2** [comment]
If I remember correctly, you have the right idea -- you need to tell the Qt Maintainance tool to install the webEngine stuff for Qt 6.7.2 .  It's separately listed
under Component Name: Qt > Qt 6.7.2 > Additional Libraries > Qt WebEngine.

IIRC, Qt Multimedia is needed, too, but those are the only 2.

**Comment by mpogue2** [comment]
Also, I'm not sure why the command line you showed above includes "ios" and "iphoneos"...that might be part of the problem.

**Comment by sharmanr** [comment]
Well that’s ok.  I thought I’d selected Qt for macos. [Sorry I hadn’t noticed ios in the command line.]

So I deleted SquareDesk.pro.user and this time it showed Qt 6.7.2 (macos) - temporary as selected as well as for IoS, Ios Simulator and macOS.  I selected just macOS and it built fine — no need to add any new Qt components from before.

Sorry to have bothered you (yet again!)

Richard

**Comment by mpogue2** [comment]
No problem!  Thanks for changing the packaging scripts!
I think we can close this one now....
