### ISSUE TITLE
Feature: remove the disclosure triangle from Lyrics tab, use Compact View instead

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#117]
Dan, here's a thought... I think the In/Out/filename-pulldown in the Lyrics tab are so useful and often used (by me, at least), and take up so little space, that I think they should always be there in the Regular View.  Maybe get rid of them only in the Compact View, using the View > Compact View menu item.  And, then get rid of the disclosure triangle, which annoys me when I end up clicking it every single time. :-)

What do you think?

**Comment by danlyke** [comment]
I think I call on a smaller screen device than you do. I'm okay with
hooking this to the compact view, though.

I don't like the disclosure triangle as-is because it looks too much
like a play button, and as much as I think transport controls on this
page would be cool, I think that's fitting in too much.

**Comment by mhkull** [comment]
I agree with Dan that the symbol used is confusing.

I do not see the need for transport controls when using it on a macbook - however I prefer key pressing much over touch screen wiping.

And finally - I have no clue what to do with the in and out values ;-) - Sorry

**Comment by danlyke** [comment]
mkhull, the in and out values right now control where the color bars get drawn. This is handy for all of those singing calls with wackily different intro end tag lengths.

I think we're headed towards using them for loop point selection, too.

**Comment by danlyke** [comment]
Okay, 83db650577dafd5c500240e670e5a203f4ef736a removes the show/hide button and uses the Menu->Compact instead. f120226f2e238d93bf083817683044824e75e091 moves the "In" and "Out" button down next to the text fields and uses them instead of the label.

Still starting with everything shown rather than in whatever view you were in last because I usually want to start that way, and only go compact if I need the browse space. Open to suggestions on that, though.

**Comment by mpogue2** [comment]
Looks great to me!  I like the way it can get even more compact in the Compact view.  
Let's close this one.  When we merge to Master, we'll pick it up.
