### ISSUE TITLE
Feature: Export song name list of selected songs

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#1178]
Is there any way to get the following:

I want to have a printed list of all of my songs marked with "duet", so I can hand it out to other callers, when we are working together. 
The list should contain record number and title. so it looks like or similar to  this:
```
ESP 177 - Achy Break Heart
RYL-0309 - Action
RB 245 - All I have to do is dream 
...
```
I can easily select the list in Square Desk so that the songs list shows the songs I want. But then ?
- I tried to mark the songs in songlist, CMD-C, CMD-P does not copy and past the songs.
- I tried File/Export Song Data - which gives me a list of every song in SquareDesk with full folder pathway

Is there any way or quick workaround to get the list exported from SquareDesk?

**Comment by mpogue2** [comment]
@Gero5 If it's only a small number of songs, you could screenshot the songTable, when you set the filter to "Duet".

That's a pretty poor workaround, though, and I really like the idea of having a way to print the current songTable, for exactly the use cases you suggest.  

Updating this issue to a "Feature".  Great idea!

**Comment by pkbott** [comment]
I like this idea too. Been tagging duets to see them but have too many tags over all. Ready to try something FUN, UNIQUE and ***@***.*** Square Dance Group:  https://www.facebook.com/groups/squaredanceforfun/On Sep 6, 2024, at 3:42 PM, Mike Pogue ***@***.***> wrote:﻿
@Gero5 If it's only a small number of songs, you could screenshot the songTable, when you set the filter to "Duet".
That's a pretty poor workaround, though, and I really like the idea of having a way to print the current songTable, for exactly the use cases you suggest.
Updating this issue to a "Feature".  Great idea!

**Comment by Gero5** [comment]
@mpogue2 'you could screenshot the songTable, when you set the filter to "Duet".' That is what I did so far. Then I tried to grab the text with Apple's OCR features, but it would paste the information column by column instead of line by line. So there is a lot manual correction effort. and it is three screens...

Ok. since I am not the only on with a demand for this... here is my idea:
There already is an implemented feature "Export Song Play History"
Maybe you can use the same export mechanism and add a feature "Export Current Song List"? 
The record number has to be added. We probably need that for Song Play History as well in future, because of new requirement from the German GEMA.

**Comment by mpogue2** [comment]
@Gero5 By "record number", do you mean "Werknummer", as found in the [GEMA database](https://www.gema.de/portal/app/repertoiresuche/werksuche)?

Since most of my songs do not have the Werknummer, that might be something that you would have to add manually.  I will also add that as a feature request, something like: "Provide a way to enter and remember the Werknummer (Work Number) required by GEMA".

I like the idea of "Export Current Song List" best, because doing this with Cut/Paste has a bunch of complexity to it (like, we already have multiple selections, so we probably also need a way to do "Select All", etc.).

When I have something ready to test, I'll put the format here for you to review.

**Comment by mpogue2** [comment]
@Gero5 Please see #1179 and provide comments there!

**Comment by mpogue2** [comment]
Fixed: 7a956bbc37b0770a29d3b502db693f7cec56ef09

Here's an example of the format of the exported CSV-with-a-header file (@Gero5 please comment!):

```
filename,tags
"/patter/RR 1323 - Diggy.mp3","Popular"
"/patter/POP - Fiery Arrow (Jiggy).mp3","HOT NEW"
"/patter/POP - Fiery Arrow (Jiggy)2.mp3,""
"/patter/RIV 1033 - Figgy Pudding.mp3","CHRISTMAS NEW"

```

**Comment by mpogue2** [comment]
@Gero5 Yep, I'll do that...

**Comment by mpogue2** [comment]
Fixed by commit: 96fd8d7fa5a0655ad73b3b8f07a1756cc3b3fdc8

The output file now looks like this:

```
type,label,title,tags
"patter","RR 1323","Diggy","Popular"
"patter","POP","Fiery Arrow (Jiggy)","HOT NEW"
"patter","POP","Fiery Arrow (Jiggy)2",""
"patter","RIV 1033","Figgy Pudding","CHRISTMAS NEW"

```

I also did a quick test with non-English characters, which looks something like this:

`"xtras","","CHARS_ñàáâäǎèéìíòóùúü",""
`

The resulting CSV file opened correctly into both Numbers (Mac) and LibreOffice (specify UTF-8 at Open time).

**Comment by mpogue2** [comment]
@Gero5 Have you had a chance to test V1.0.11 with your list of songs?  If so, let me know if it looks OK (especially checking any filenames containing characters with diacritical marks, like ü, etc.)...

**Comment by Gero5** [comment]
I am working with V1.0.9. Where can get V1.0.11? It is not in the google drive folder called SquareDeskReleases.

**Comment by mpogue2** [comment]
Hmmm....I think the email might have been lost!  I'll try inviting you again to the PreRelease folder on Google Drive.

Sent email to you directly with a link!
