### ISSUE TITLE
Bug: performance problem with Show All Ages

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#121]
It takes ~5 seconds of beach ball to go in and out of that mode on my Mac laptop (which has 8 cores)...

**Comment by danlyke** [comment]
Aha! I just instrumented some timers. The time on Linux was all happening within

` ui->songTable->item(i,kAgeCol)->setText(age == ages.constEnd() ? "" : age.value());`

I tried turning off the `updatesEnabled` property, no joy, but then I discovered  http://www.qtcentre.org/threads/15979-QTableWidget-setItem-very-slow-the-second-time and now I hide it before the update and show it after, order of magnitude better speed.

Fixed in f039ca62733222c43ed8be3c0d3459699c2e3b65 (with some whitespace conflict management in 34647929fd2df149f5fc8bffba58ab34898e173b )

**Comment by danlyke** [comment]
(hopefully that order of magnitude transfers to Mac, too...)

**Comment by mpogue2** [comment]
Yes, that order of magnitude transferred just fine to Mac OS X.  Session and Show All Ages are now plenty fast.  Closing this one...nice fix!

**Comment by danlyke** [comment]
I think I'm going to build an "updating stuff" wrapper object that we can instantiate to turn off all of the updating on these things, and the destructor will turn it back on, and we can have it in one place...

**Comment by mpogue2** [comment]
Sounds good...
