### ISSUE TITLE
Bug: Hotkeys don't remember multi-character sequences

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#246]
For example, I can enter Cmd-Shift-L, and it looks like it took it, but if you OK the preferences dialog and come back in, it didn't remember it properly.  Works OK for single characters (e.g. "Q"), though.

**Comment by mpogue2** [comment]
Also, "=" doesn't seem to work as a hotkey at all.

**Comment by danlyke** [comment]
Yeah, I think we perverted the multi-keypress bits of the control to do multiple keys for the same action (because we switched to an action first mechanism). Should probably expand this out to a table so that you can choose up to 3 keys for each action.

**Comment by danlyke** [comment]
Okay, I'm addressing this, because we need to be able to map the full QKeySequence to deal with things like Bluetooth remote inputs.

**Comment by danlyke** [comment]
Mark Hart on Facebook got a cheap Bluetooth volume control, and because we use keys rather than key sequences, it isn't working. https://www.facebook.com/groups/callercuers/permalink/2148674741825675/

I think what we want to do is get away from the global event filter in almost all cases, and move to shortcuts. I'm trying to figure out how best to manage QShortcut objects, I think we'll have to create a grid of them that roughly matches the assignment capabilities in the hotkeys editor, say 3-5 attached to each KeyAction so that we can assign that many keys to each action.

I don't see a way to enumerate the QShortcut objects attached to each window...

**Comment by mpogue2** [comment]
> I admit to not knowing how shortcuts work...I am dubious that getting away from global event filter will allow us to keep existing functionality , but I’m willing to be wrong...let’s do this in a branch to check it out before committing to master.

What is the key mapper that was referenced?  I currently use BetterTouchTool on Mac OS X which has some key mapping capabilities I believe...

**Comment by danlyke** [comment]
I don't know which keymapper Steve Stout is using, I asked him on the Facebook thread.

The volume control is this: https://www.ebay.com/itm/Wireless-Bluetooth-Media-Remote-Control-Button-Car-Steering-Wheel-Bike-Handbar/222190371306?hash=item33bb9401ea%3Ag%3A99sAAOSw8gVX7Myk

I have one on order, though of course I'm gonna make it work with Linux first (but I think, if I can get the shortcuts stuff ironed out, that that'll be cross-platform).

**Comment by danlyke** [comment]
Hmmmm... That was scarily easier than I expected. Maybe. Check the "hotkeys" branch. We probably want to move the remaining things from the global event filter over to the QShortcut mechanism, but this gives us 5 possible shortcuts per action, and allows for multi-key shortcuts.

**Comment by danlyke** [comment]
So I didn't really mean global event filter, I meant simplifying MainWindow::handleKeypress (which is fed by the global event filter), but it's probably okay as-is for now...

**Comment by mpogue2** [comment]
Ah...makes sense!
I like what you have so far, although it's kinda buggy:  The shortcuts seem to change every time I come in.  #17 (Toggle) was T in col 2 and also T in col 3.  Then it was "Press shortcut" in col2 and T in col 3. Also, Test Loop (#8) was Q, but also Tempo +'s second Hotkey was Q, but the next time in, it's not.  Is it also sorting them, when I exit the dialogue and come back in?  

I seem to be able to set multi-character hotkey sequences, which is nice.  I played with that for a while, and it works as-expected.

One minor suggestion: Hotkey/Hotkey/Hotkey/etc -> Hotkey 1/Hotkey 2/Hotkey 3/etc.

**Comment by danlyke** [comment]
Hmmm.... I'll look again at save and restore, that's where I was having the problems. And sorting them.
I like numbering the hotkey headers.

**Comment by danlyke** [comment]
Okay, I have sorted the hotkeys (though I may have to make a custom sort function, because "P" shows up before "Space", but "S" shows up after "Right", we should probably multi-character labels sort after or before the single character labels/keys). 60623563cc124d52257c4f6af8e5c3a8f06cad25

I also have no idea how duplicates could have been showing up in the table, because the input to setting up that table is a hash indexed by keypress name, so it's not like we could get multiple ones on input. So I explicitly null out the keypresses for the unused inputs in that table.

I have numbered the columns. aa036e4c372633a76017c4e2232f00e4e7b008a5

**Comment by danlyke** [comment]
5c8cd91912abf11f8f8006e593d6c4f4a009f490 sorts long key names before single characters, and something got an empty key assignment, which gave a weird blank setting in the first column, so I fixed should that happen.

Also need to figure out how to integrate this with #217 correctly.

**Comment by mpogue2** [comment]
@danlyke  I took a look at the hotkeys branch, and found a couple of bugs (overall, it's looking good, I think):

1) Cmd-UpArrow doesn't work as a shortcut, but it should (UpArrow alone seems to work fine).
2) When I try to replace Q with W, and I quit and come back in, it didn't replace Q, it still has Q and it added W.  I'm not sure how to replace a shortcut (or delete one, for that matter!).

**Comment by danlyke** [comment]
Hmmm... I don't have a command key, but alt-uparrow works.

On the Q/W thing: I'm loading a set of defaults, and then overriding them. I don't know how to do deletion, but at the very least I should make sure that when we assign a new key in the editor, we make sure we've removed it from all other columns rather than just letting it fall out...

**Comment by danlyke** [comment]
Meta (Windows key) up and down works, but there's something weird about focus with it: It worked, then a menu flashed, then it didn't work 'til I clicked back in the window (this is all on Linux).

**Comment by danlyke** [comment]
And I exposed the "<unassigned>" action, for when you really want to keep a key from doing anything. 85b3bcc7203600be554a6217bd86db05a09dc73d

**Comment by mpogue2** [comment]
OK, here's what works as of Top of Master (0a20b72d6559e4f0beac1654cf8224ed63e7d6bf):
- setting a shortcut to a single letter, like "D" or "U"
- it's both immediately usable after Preferences dialog close, and it's remembered across app restarts
- Hitting just the Command or Shift key to clear out a shortcut

What doesn't work:
- Any shortcut key that involves Modifier keys, like Command, Control.  
   It accepts it, and shows the right thing in the field, but it's not active, and not remembered when
   the Preferences dialog is closed.  example, Cmd-U, Cmd-Shift-U.  When you come back in,
   the field just says "Press shortcut", as if nothing is set there.

**Comment by mpogue2** [comment]
@danlyke By the way, the "Switch to <tabname>" hotkeys were a great idea!!  I love it!

**Comment by danlyke** [comment]
Wait, top of branch 'master', or top of branch 'hotkeys'?

I've been doing all the hotkey stuff in the 'hotkeys' branch. If we're
close enough to merge that back into master (and I think we are), then
I will.

Because the modifier keys work at the top of 'hotkeys'.

**Comment by mpogue2** [comment]
7c4603d3d0e9c8cc9c26b7c9a377582fb5678092 is Top of branch "hotkeys".    You might be looking at an older comment I made.  I realized that I was looking at Master, and so I edited the comment, completely rewrote it to apply to the Hotkeys branch.  

Just the three problems with Hotkeys branch:
- pressing the Command key to clear is not persistent (if this is fixed, I think we can get rid of the "unassigned" row completely -- it's not intuitive, I think)
- Reset to Defaults doesn't seem to rest the new "Switch to X" hotkeys, and hilarity ensues.
- column 1 is wider than the rest (is this because it's expandable, and the others are not?) -- this is MINOR

If you could fix the Command key persistence bug (and delete the "<unassigned>" row), I think we should merge Hotkeys to Master, and then fix the reset to defaults bug whenever you can...

**Comment by danlyke** [comment]
Okay, fixed those three, merged into Master.
