### ISSUE TITLE
Bug: Alpha 3 does not setup the Intro point correctly for singing calls

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#264]
It seems to be zero, and when I set it to something else, it's not remembered.
Hmmm...I wonder when this stopped working?

**Comment by mpogue2** [comment]
I have not checked for earlier than Alpha 3 yet.  But, it's bad in A3 and beyond.

**Comment by danlyke** [comment]
Hmmm... I noticed this on my calling laptop, but thought I was just
hallucinating or needed to do something else because setting times
seems to be working fine on my dev laptop.

Under the Music menu there's a "Reset In/Out/Loop Points" which does
work to get back to something semi-ok in a pinch, but I'll see if I can
find a little time to dive into this.

**Comment by mpogue2** [comment]
Any luck?  If not, I'll spend some time tonight to try to root cause it to a single build, at least.

**Comment by mpogue2** [comment]
Yeah, I broke it in 41c7d029e19c3cdf1159207f378cc3ae1565652d.  I'll try to figure out what I did wrong!

**Comment by mpogue2** [comment]
Fixed by 84caa9bc01c95b461b02706b5d6a9eb98a8509b1 .
