### ISSUE TITLE
Cuesheet styling with edits not working on Linux

### ISSUE THREAD

**Issue by danlyke** [mpogue2/SquareDesk#335]
Not sure what's going on, but ...

Unlocking a cue sheet and clicking on any styling gives a too small to be usable font. Saving pops that font back up to something that's about normal text size, but not styled as I'd expect.

This seems to occur even with something where 

`<LINK href="cuesheet2.css" rel="STYLESHEET" type="text/css">`

exists in the document when it's loaded, and where cuesheet2.css exists both in the pwd of the application and in the target directory of the cuesheet file.

**Comment by danlyke** [comment]
Also doesn't work when path to the stylesheet is hardcoded as an absolute path, even with a preceding `file:///home/danlyke/...`

**Comment by danlyke** [comment]
So it looks as though on save some of the stylesheet edits are getting applied directly to the elements, which would be why some styling is showing up after the save.

It'd also be nice if the italic and bold tags stayed italic and bold rather than being over-specified spans.

I'd really feel more comfortable if we could go back to semantic markup rather than doing all of this explicitly appearance-based markup.

**Comment by danlyke** [comment]
Basically, on Linux cuesheet editing is broken enough to be unusable, any attempt to style makes the text small and unstyled, with the only bright spot that once you save the areas that got some style applied go back to at least being kinda the right size.

**Comment by mpogue2** [comment]
@danlyke I'm starting to look at this...the problem doesn't seem to happen on Mac and Windows, at least with the cue sheets I've tried.  Could you post one of the cue sheets that has the problem you describe?

To give you a little more context here, the way the Lyrics editor works is that we're using what is essentially a Qt-based HTML presentation editor.  It has literally no understanding of semantics (as is true of many HTML editors -- they are not XML editors, and they only work well with presentation semantics).  So, the cue sheets are changed (under the covers) from semantic tags to appearance tags on the way in, and then changed from appearance tags to semantic tags on the way out.  When we save, it also tidies up the HTML so that it is guaranteed valid and correct HTML, and then it re-reads the entire file (re-converting from semantic HTML to appearance HTML).  This is to ensure that all the changes were made correctly.

The cuesheet2.css file is not used, because it basically changes the presentation in ways that the Qt widget doesn't really fully understand.  This was a source of many bugs.

There are still bugs here, especially when a cue sheet is imported without doing a "clear formatting".  The existing formatting (even though hidden in many cases) is not handled well (or even consistently) by the Qt HTML editor widget.  These bugs are hit especially when importing text using cut/copy/paste from a PDF document, or from an existing HTML file that is already formatted.

To get around this, the easiest thing I've found is to immediately select everything and do Clear Formatting on load.  That removes all the existing presentation markup (which might not even be valid HTML).  Then, it takes about a minute to re-apply the desired markup to the cuesheet.  At that point, the HTML is guaranteed to be valid and correct.

**Comment by mpogue2** [comment]
Some more comments:  Font size is particularly a problem with Qt.  It just is not cross-platform at all, when it comes to font sizes, due to underlying different philosophies on the three platforms.  That's why we have a LOT of #ifdef's around the font size stuff.  It needs to be hand-tuned for each platform.  This is a known limitation of Qt.

If you could post a cue sheet (and maybe a screenshot?), I can check it here in both Mac and Win, to see whether it's something specific about that cue sheet that you're hitting (that we can probably fix by a bug fix on the import side), or whether it's likely to be some thing very different about the Qt HTML editor widget that is specific to Linux.   I am suspecting the latter, because Mac and Win use WebEngineWidgets (based on Chromium, with better HTML compliance), while Linux is using WebKitWidgets (Apple's WebKit).  

The Qt rationale for moving to Chromium is here:  http://blog.qt.io/blog/2013/09/12/introducing-the-qt-webengine/ .... it's been out for 5 years now, and all new development is happening there.  Is it possible that this is the difference that is causing problems on Linux?  

Please post a cue sheet that has problems, and I think that will help to narrow down the problem...I agree we should find a workaround for Linux, if it's not working there.

**Comment by mpogue2** [comment]
I'm also going to open up a separate Issue on this one:  "It'd also be nice if the italic and bold tags stayed italic and bold rather than being over-specified spans."

**Comment by mpogue2** [comment]
OK, #336 is fixed.  But, in looking at the code, I don't see any special copying of the internal cuesheet2.css resource file happening for Linux, like we have on Mac and Windows.  

The lyrics editor needs access to the internal CSS file, so it can reliably translate from semantic HTML into presentation HTML for editing.  It then does the reverse translation at save time, assuming that the internal CSS file was used at load time.  If that file is missing on Linux, I suspect that the lyrics editor would be fairly broken.    BUT, in that case I would have expected you would see a message on Linux, from line 1809.  

So, I'm now thinking that maybe Linux is picking up a non-internal CSS file (in which case I would expect much breakage in the editor...)?  Unfortunately (sorry!), I did not change the name when it was moved internal (which would have made it more obvious if the wrong one was being picked up).  

@danlyke could you check to see if you are picking up the internal one?  The internal one is in "other files" in the .pro list on the left hand side of QtCreator.  That needs to be copied to wherever Linux picks up its resource files (GetResourceFile).  If it's not picking up anything, you should have seen the warning message.  If it's picking up a non-internal one, it would fail silently.  Line 1806 is where to look.

**Comment by danlyke** [comment]
I have tried both making sure there's no other cuesheet2.css that it'd find, and trying to copy one into places where I think it'd load it. I have seen no error messages.

Here's what happens when I start with no cuesheet and click on each of the styles in turn. Interestingly, from a clean file they don't switch to something else when I save. But not particularly that "Clear", the results of highlighting that text and clicking "Clear Formatting", is larger than the other text.

![squaredeskcuesheetissues](https://user-images.githubusercontent.com/88919/38505035-15d26ca6-3bcb-11e8-847f-492da7dee6a3.png)

(I didn't do a baseline text because the "Title" through "Lyrics" didn't change when I modified things.

If I go to https://www.ceder.net/recorddb/viewsingle.php?RecordId=1776&SqlId=20610 click on the Color cue sheet, save that, and pull it up in SquareDesk, I get this:

![squaredeskcuesheetissuesfreshload](https://user-images.githubusercontent.com/88919/38506229-17e01194-3bce-11e8-8b21-516249b830fd.png)

If I save that file, it turns into this:

![squaredeskcuesheetissuesaftersave](https://user-images.githubusercontent.com/88919/38506243-23c3ddec-3bce-11e8-9c1f-66bb8882a732.png)

If I highlight "Opener" and click "Header", and highlight the first two lines of lyrics and click Lyrics, I get this:

![squaredeskcuesheetissuesaftersavewformatting](https://user-images.githubusercontent.com/88919/38506301-47959576-3bce-11e8-86dd-1c82ccab36d5.png)

If I save that, it goes back to the "after save" appearance.

The top of the saved cuesheet has the `<LINK href="cuesheet2.css" rel="STYLESHEET" type="text/css">`, 

At line 1608 of mainwindow.cpp on the master branch I see the commented out qDebug output of the TidyInput strings, is that where I should be looking for error messages about included stylesheets?

**Comment by danlyke** [comment]
Oh, I see: getResourceFile needs a bunch of ifdefs removed...

**Comment by danlyke** [comment]
Is there code ifdefed in?

**Comment by mpogue2** [comment]
I'm glad you were able to track this one down!  
Just to follow up on your question:  The LINK is used only by the saved file.  When it's read in, the LINK is removed, and it's put back in when the file is saved.  This allows the cuesheet2.css file to be used by other programs, but it always uses the internal one inside the SquareDesk lyrics editor.  An arbitrary CSS file can do a lot of things to mess up editing, since the editor widget is not really an HTML/CSS editor.

**Comment by danlyke** [comment]
Excellent.

Yeah, I suspect there may be a few other places where we have #ifdefs
in place that I haven't put in the alternative (or just removed) for
Linux...

Anyway, this one's in, which is good!
