### ISSUE TITLE
Feature: enhanced copy functionality in sd Current Sequence tab?

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#351]
OK, I was intensely using SD the other day to make up sequences for a dance, and I could not figure out how to copy the entire SD sequence.  After playing with it just now, there currently seems to be exactly one way to do this:  highlight all the lines in the Current Sequence tab, and then control-click/right-click to get the context menu, and select Copy.

I had no idea it worked that way...
As an SD user, I expected either:
1) I could highlight the entire sequence and then hit Command-C to copy it (this currently does nothing at all to the copy/paste buffer), OR
2) the Copy item in the context menu would copy the entire sequence (it currently only copies the highlighted items), OR
3) the context menu would have a "copy entire sequence" item I could choose

So, this is a request to do one of the above.  I'm not sure which would be best.  @danlyke and @olldray , which of the above would be what you would expect to work?

In the mean time before we have the whole sequence designer thing, maybe some some extensions to Copy will tide us over pretty well until then.

My workflow is generally to design a modular sequence in Notes, then I test it in SD.  If incorrect, I want to copy the whole dang thing (bonus: now in standardized format!) back to Notes (which gets auto-replicated to all my Apple devices).   If I am reading a sequence, then I can read it directly from an iPad or iPhone or MacBook.  If copy works well enough, I would probably start in SD, and then copy the whole sequence to Notes for replication.

**Comment by danlyke** [comment]
So playing with this more: I fired up SD so I could copy a formation diagram, so I'm even more in the "just copy selected sells" camp. But I have added select all (including cmd/ctrl-A) to the current sequence table.

**Comment by danlyke** [comment]
Okay, I'm completely braindead and tired from a week of conferencing, but I think I have a solution: Add a "Copy Options" menu to the bottom of the context menu. The submenu for that lets the user choose between the 3 different possibly copy behaviors, these are static between runs, the default is your preferred behavior.

Similarly, that sub-menu has options for different HTML stylings.

And I add a "Select All" shortcut, and make sure that the various hotkeys operate on the sequence table rather than just the line edit.

Commit coming in a little bit...

**Comment by danlyke** [comment]
Feel free to re-open this if the behavior in  58b826f6e7918fdc4e40008d9eddc441b962adcd needs further tweaking.
