### ISSUE TITLE
Update Taminations directory in the repo

### ISSUE THREAD

**Issue by danlyke** [mpogue2/SquareDesk#360]
So I'm noticing that Brad's done a huge update to Taminations. I'm not sure what all we're using the Taminatons incorporated into our repo for; is there any reason I shouldn't update it?

**Comment by mpogue2** [comment]
Feel free to delete Taminations from the build tree.  I don't think it's used right now.
At one point, I was going to build it into the app, so that it's pre-installed.  Perhaps nearly as good would be something in the Startup Assistant that allows you to "download and install the latest Taminations".  I can't see making a menu item for this, but the Startup Assistant might work well.

**Comment by danlyke** [comment]
I have dreams of using the Taminations animation data for SD, but that's not on my radar just yet.

**Comment by danlyke** [comment]
Okay, then I'm gonna remove it, and my scripts to import the Taminations animation data will take another directory as input, just for ease of maintenance.
