### ISSUE TITLE
Bug: Changes to playlist are not saved when program is closed

### ISSUE THREAD

**Issue by mhkull** [mpogue2/SquareDesk#40]

**Comment by mpogue2** [comment]
I never thought that we might want to save the current playlist numbers, but that's an interesting idea!
Currently, the "official" way to do this is to do Playlist > Save Playlist..., but I like your idea to make these persistent.  I'm not sure yet how that will interact with Guest Mode, where a second database is involved.  We'll need to think about this some more...  Thanks for the idea!

**Comment by mhkull** [comment]
My point was: When I put together a playlist for my next event, I work on the list. I open it, make changes to it, close it again, next day open it, make changes to it and then, when I have an open list and I close the program I expect: Save changes to playlist?

Frankly, I do not understand the idea I gave to you ;-)

**Comment by mpogue2** [comment]
Ah, so changes to the # column should be persistent, whereas today they are temporary.
I think I understand (and I agree with this idea).

**Comment by mpogue2** [comment]
Fixed in b68a4be82b57cb024ea15f998df8a4b8ce4cbd10 .  There is now a hidden playlist (.squaredesk/current.m3u) that contains the current playlist state (if you're in the middle of editing it).
If you don't use playlists, nothing changes.  I put it into a playlist file, in case the user wants to copy/paste/edit it manually with external tools (e.g. a text editor, an M3U playlist editor).  Note that M3U files still use absolute pathnames, so moving the Music Directory around will likely not be able to see the current playlist songs.  The current playlist state references songs of the main caller, not of the guest caller in guest mode (those probably won't work).
