### ISSUE TITLE
Bug: Performance on Windows and non-user directories is awful

### ISSUE THREAD

**Issue by danlyke** [mpogue2/SquareDesk#422]
A lot of people have their SqView music in C:\Music or C:\SqView. Performance on the two Windows machines I've tried to run SqView on has made it completely unusable. I got somewhat usable when I copied a subset of the music over to a user directory, but maintaining that second directory tree wasn't going to work out well for the user in question.

I suspect that something's triggering the directory scanning/reload code. Making disabling this a preference might help, as might putting in some sort of debouncing.

**Comment by mpogue2** [comment]
@danlyke Performance of what operation is slow?  The file watcher only kicks in (or should kick in!) when a change is made to the Music Directory.  No changes, should be no file watcher triggers.  

The overall music scan might be slow, and that's true on all platforms, especially with a large number of songs.  I'd prefer to see us speed up the scan process (on all platforms), rather than providing a preference to turn it off.  If the file watcher is getting triggered repeatedly, then I do agree that debouncing by time would be a good thing!

**Comment by danlyke** [comment]
Everything is slow. Like seconds to minutes for response to any attempt to do anything. Move the music into something under the user's Documents directory and it's better, though still not great.

I'm assuming it's the file watcher, but it could be something else.

**Comment by mpogue2** [comment]
Hmmm...That does not occur on the other installations I've worked with on Windows...it is slow starting up, but once up, it seems to work fine.  Maybe on that laptop, it's a slow CPU, and there are also a lot of songs in the song table?  

Performance is definitely lower with a lot of songs!  I've already spent a lot of time optimizing what's there now, and to get to the next level of performance will require some major changes to song table, I think.  I'm in favor of this, because it will likely improve performance on all platforms!

**Comment by danlyke** [comment]
It's on two machines that work absolutely fine with SqView, so that's
my benchmark. It may be a number of songs issue. I'll see about
borrowing one of those laptops so I can do some more debugging (and
maybe try to set up a Windows dev environment; I realize that I
probably also went about setting up the Mac dev environment in the
wrong way).

I don't think it's a ton of songs in the song table, I think he's
probably got a few hundred 'cause he's pretty aggressive about culling
alternate versions, but, yeah, we definitely need to get to the next
stage in song table management. The fact that filtering stops working
after a thousand songs is super annoying, and there are a bunch of
features that going to a data model will fix.

**Comment by mpogue2** [comment]
Some thoughts:  I have ~400 MP3 files, and it's decent speed even on Windows in a virtual box.  But, I also have an SSD, not spinning iron.  The parsing of the files (and matching of filenames) should only happen once at startup, and when saving a lyrics file.  If you are seeing slow performance with only a couple hundred files, and it's slow all the times, like MINUTES slow, then maybe that laptop is short of memory and/or CPU, in addition to having a regular non-SSD disk drive?

It will be interesting to see how much positive effect on performance moving to a data model will have!

**Comment by danlyke** [comment]
Both laptops have SSD, both have a decent amount of memory.

I'm pretty sure the problem is that something's triggering the
directory watcher and just causing continual song reloading.

I don't know what I'll need to do to put together a dev environment for
Windows, but I'm gonna get one of the laptops from Doug so that I can
experiment further.

**Comment by mpogue2** [comment]
OK, that's definitely a problem, especially if they have SSD's already.  It might be easy to put a qDebug() statement at the point the FileWatcher kicks in to see if it is triggered any more than expected.

**Comment by mpogue2** [comment]
Attaching ZIP file here.  It's what I used to test, but it's a debug version, so it might not work in the regular release environment.  I have no way to deploy debug versions at this point...sorry...
I might have to build a special release just to test this (when I get some time to do so...)
[SquareDesk.exe.zip](https://github.com/mpogue2/SquareDesk/files/2490518/SquareDesk.exe.zip)

**Comment by danlyke** [comment]
Thanks, I'll get to testing this weekend (calling tonight). I should
figure out how to get a Windows dev environment running too.

**Comment by mpogue2** [comment]
8d52970b425a73c237cd8998c8c7c24382c5d928 provides a ~2.5X improvement in app start time, and a ~20% improvement in song load time.  It also enhances the PerfTimer class to provide a bit more info:  line numbers, an elapsed() call to show both absolute elapsed and delta/incremental (since the last elapsed() call) times.  You can enable the PerfTimer output by uncommenting the ENABLEPERFTIMER line in perfTimer.cpp .  There's probably more that could be done here with macros, to avoid having to manually pass in __LINE__ each time.

I turned off the FileWatcher for now (with an #ifdef), because **initializing** it was taking a huge amount of time, and it was proportional to how many files were in the watched directories.  I also deleted some status line updates, that took a lot longer than expected (that hit was taken at song load time).  I also got a big win from moving the songTable font initialization to BEFORE the songTable was populated with songs -- changing fonts after the songs were loaded meant that all existing songTable entries needed to be updated, and this does NOT need to be done if they are constructed with the right font and stylesheets to begin with.

On my MacBook, app start time went down from about 3.5-3.6 sec to about 1.3-1.4 sec.  I suspect the win might even be larger than that on machines with a spinning iron hard drive, or on platforms (Windows, maybe?) where the FileWatcher was implemented even more inefficiently.

Might still be a performance win to implement the MVC songTable, but for now I think this change will be a Big Win for our users, and it will buy us some time to work through the MVC songTable (which I suspect is a much bigger change).

Sorry for not splitting it into itty bitty commits with one main change per commit!

I'll have to build a release for Windows, and then please let's get this release to your user who was having massive performance problems to see if any of these changes help!

I will open a new Issue to take care of how to refresh the songTable, for the case where a new file is dropped into the Music Directory.  At this point, the songTable will NOT update automatically, and that feature (which was quite handy) is disabled.

**Comment by mpogue2** [comment]
@danlyke Please try version 0.9.2 alpha9a (now in Dropbox) .  It includes a couple of performance fixes (documented elsewhere), and it also fixes some Windows-specific bugs.  It seems to perform pretty well on Parallels on my 2017 MacBook Pro 13", but I think we need to hear from your Windows user to understand whether we're fast enough at this point on Windows.

**Comment by mpogue2** [comment]
@danlyke This is the bug fix I was referring to when we spoke yesterday.  I'm inclined to mark as fixed at this point, especially in the light of my intent to dial back on Windows support.

**Comment by mpogue2** [comment]
Latest branch, flexible_audio, should fix this, or at minimum make it about 3X better.  The FileWatcher does not wake up as often, and when it does, it doesn't scan as many files.  Of course, we really are not doing much with Windows at this point, so perhaps this is moot.

**Comment by mpogue2** [comment]
I think this problem is not present in the new code, and right now we're not supporting windows anyway.  So, closing for now.  Reopen if this is a problem and we bring the Windows version back.
