### ISSUE TITLE
Songs don't play...crash program instead

### ISSUE THREAD

**Issue by pkbott** [mpogue2/SquareDesk#550]
I have a number of songs that are MP3 files that I use for patter and singers both that when I upgraded from the last bleeding edge version to the current one now crash SqDesk and won't play.  Where can I get a copy of previous version again?  There were new songs purchased this morning as well that I added today and they only crash the program as well.  I have over 30+ songs so far that just crash the program.  I am on 10.15.4 Catalina currently.  Looking for help...

**Comment by mpogue2** [comment]
Thanks for the bug report!  I think this one is probably the same as #532.  I'm working on a new release that should fix this.  In the meantime, the workaround is to turn off Replay Gain, and rename (even by just one character) the files that were crashing.  They should stop crashing, and if they do, it's almost certainly due to #532, which was very tricky to track down.

**Comment by mpogue2** [comment]
Believed to be the same as #532.  New version just released appears to fix the problem.  Closing as Fixed.  Thanks for the bug report!!
