### ISSUE TITLE
Docs: Not easy to build SquareDesk on MacOS, due to lack of documentation

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#723]
This Issue will be used to track the problems that a MacOS programmer new to SquareDesk has
in getting a build up and running.

**Comment by mpogue2** [comment]
1) There's no README.txt file that tells how to compile, or what the minimum requirements are.  Right now, SquareDesk Master branch compiles and runs on M1 Monterey (ARM) and X86 Big Sur (X86).  The X86 version runs correctly on M1 MacBooks using Rosetta, although it runs slower than the native version.  Macports and Brew versions of Qt are not supported (reported not to work, too).
2) Toolchain is Qt/Qt Creator from the Qt website.  Other toolchains may work, but they are not tested.
3) SoundTouch needs to be built separately via cmake (https://github.com/mpogue2/SquareDesk/issues/606#issuecomment-974615102) in order to generate soundtouch_config.h.

**Comment by mpogue2** [comment]
4) Need to document what version of Xcode and the Mac libs are required.  I believe that needs to be updated when it changes, because it's hard-coded in a .pro file.

**Comment by sharmanr** [comment]
5. Several extra libraries are required for Qt [at least for Qt 6.3.2]; otherwise there are errors like
`Unknown module(s) in QT: webenginewidgets multimedia`

The following extra modules make it work:
`Webengine,  WebChannel, WebSockets, Positioning and Multimedia.`
[I’m not sure all those are needed, but most definitely are.]


6. There is a problem building soundtouch:
 .../SquareDesk-master/SquareDesk-DEV/test123/soundtouch/soundtouch.pc.in does not exist.
 .../SquareDesk-master/SquareDesk-DEV/test123/soundtouch/SoundTouchConfig.cmake.in does not exist.

The following recipe fixed it:

> cd
> mkdir soundtouchtest
> cd soundtouchtest
> git clone https://codeberg.org/soundtouch/soundtouch.git
> cd soundtouch
> cmake .
> make -j

Then moved the result soundtouchtest  directory to the source.

With those changes (items 5 and 6( it built on an M1 mac running 12.6 (Monterey).

**Comment by mpogue2** [comment]
#6 above has been addressed.  The files needed for Soundtouch to compile are now in git .
So, after downloading the SquareDesk source from GitHub, 
manually cd to the soundtouch directory, and type:
```
cmake .
make -j
```
and the library `libSoundTouch.a` should be built in test123/soundtouch.  This library will be linked in later as part of the normal SquareDesk build.

**Comment by mpogue2** [comment]
SquareDesk-DEV/README.txt now contains a list of prerequisites, instructions for how to build, hints for debugging, and how to package for distribution.
