### ISSUE TITLE
Feature:  User supplied default templates for singer and patter songs

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#729]
I think it would be nice if users could have their own "default" cuesheets for singing and for patter songs.

- The default lyrics cuesheet (Make some cuesheets by morning) is cute but very long and typically requires removing a lot of stuff to make it suitable
-  Some users would like having a two-column initial cuesheet (see issue #728)
- Some users might prefer other differences, such as different colours perhaps.

How would the user manage a "personal" lyrics or patter file?  Where would be it stored?

I think this could be done by simply checking for the existence of `lyrics.template.html `in the lyrics directory (or `patter.template.html` in the patter directory) since these are directories the user is presumably cognizant of.   (I assume the .squaredesk directory is not meant to be tweaked with my the casual user!)   If the file exists then use it, otherwise proceed as before with the resource file.

**Comment by mpogue2** [comment]
I like this idea, and it's pretty straightforward to implement.  The .squaredesk folder is indeed default hidden (intentionally), but we could also just document how to see it and modify the two template files.  Shift-Cmd-<period> toggles visibility in Finder.

**Comment by sharmanr** [comment]
I think keeping user changes out of the .squaredesk file is a good idea.   Having the user add an extra file in the lyrics (or patter) directory seems straight forward.

**Comment by mpogue2** [comment]
Agreed.  As clearly an advanced user, feel free to use Shift-Cmd-<period>, until we get this implemented. :-)

**Comment by danlyke** [comment]
We put the singing calls lists in reference, seems like as good a place as
any to copy the user modifiable stuff.

**Comment by danlyke** [comment]
Errr, not the singing call lists, the teaching lists.

**Comment by mpogue2** [comment]
It turns out that the templates were NOT in the .squaredesk folder.  On MacOS, they were in the Resources folder inside the app itself -- considerably harder for a user to find.

OK, so user-defined template overrides are implemented now, in their respective folders, as @sharmanr suggested.

If a template override file is present, will be used in place of the default ones that are embedded into the Resources folder of the app itself (e.g. Mac OS).  Note that a user-defined template override must be put into the correct directory:
- lyrics -->  <musicDir>/lyrics/lyrics.template.html
- patter --> <musicDir>/patter/patter.template.html

By putting them in their respective folders instead of the <musicDir>/reference folder, we don't have to filter it out from the Reference tabs, and it's also extensible to whatever directories the user decides to create.  I think @sharmanr's intuition was the best approach on this one....

Fixed by d7dee241796e67363b0473f9cf4434d68ff378ae .

**Comment by mpogue2** [comment]
One more comment:  Note that the lyrics editor does not currently support user-defined colors.  The colors are currently always overridden (that is, they are literally replaced within the file) in a way that allows us to use Qt components for HTML editing.  This is definitely a kludge (from "klug" in German meaning "clever", it is said), but it seems to work OK, given the limitations of HTML editing in Qt that we have to work with.
