### ISSUE TITLE
Displaying the song timer when a cue sheet is visible

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#737]
One thing I missed from SquareView was that when displaying a cuesheet there was a counter showing the current time in the song.  I found this very useful for a few songs where the timing of the words was tricky. (This can be especially handy when you can’t hear the music well from the stage.)

Another place where displaying the current position in the song can be useful is when adjusting the start and end loop positions of patter calls.

The attached patch implements this in SquareDesk by duplicating the song timer of the MusicPlayer tab onto the Lyrics tab, putting it at  after the slider and the  label that shows the current figure.

[songtimer.patch.txt](https://github.com/mpogue2/SquareDesk/files/10149553/songtimer.patch.txt)

**Comment by mpogue2** [comment]
I love this change!

Made two minor changes to your change:

1) Made the currentLocLabel_2 pay attention to the setting on the "Experimental" tab called "Show time remaining instead of current position in song.
2) Deleted some end-of-line whitespace.

Note that the "Experimental" tab really hasn't been experimental for a long time.  Probably should be renamed at some point.

Fixed by: e7f67fd265724ace483251677ec3bf7cf9e27e65

**Comment by mpogue2** [comment]
If this fix seems acceptable to you, go ahead and close this Issue (can you do that?  If not, just comment here, and I'll close this one.)

**Comment by sharmanr** [comment]
My apologies...  I had added a comment but must have not finished it.   The only comment was that line 926 is the same as line 925;   in line 926 it should be ui->currentLocLabel_2 not ui->currentLocLabel_2  (though it doesn't seem to matter).
Otherwise it looks fine.
![temp](https://user-images.githubusercontent.com/76225465/206967087-ade1c9f0-f2df-4cd6-9ffa-388ed7a58ced.png)

**Comment by mpogue2** [comment]
Fixed that one...nice catch!

**Comment by sharmanr** [comment]
I thought I had closed it,  let's see if this works...
