### ISSUE TITLE
Display the flashfile name if there is one

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#755]
The implementation of Issue #748 doesn't show what flash filename was chosen if one was.  So, if a caller has two or more flashcard files, perhaps for different clubs, the item has to be unchecked and then rechecked to specify a filename.

Here is a simple fix.   When there is any change, for example selecting a file or unchecking the item,  the menu item is updated either with the basename of the file if there is one,  or the string "Select a file" to indicate a file needs to be chosen because the item is unchecked.
[showFlashFile.patch.txt](https://github.com/mpogue2/SquareDesk/files/10442664/showFlashFile.patch.txt)

**Comment by mpogue2** [comment]
Commit: 543efbb54f722f925aadc0f16cace8a43fb78ad0

I'm wondering though, whether there might be a simpler way?  When using this implementation, I found myself thinking that clicking on [X] Mike's List would give me [  ] Mike's List, but instead it gave me "Select a File".

I'm thinking it might be somewhat easier to use, if the user-selected filename worked exactly like the other possible selections(the built-in ones, e.g. basic, ms, etc.).

Maybe something like:

If there is already a "user file" selected, looks like this:
```
View
   Flash Call Levels
      [X] Basic
      [ ] MS
      ...
      [ ] C1
      [X] <I>Mike's List</I> <-- Normal menu item, but italic. Click to toggle, just like the above.
      --------
      Select a <I>user file</I> <-- opens the dialog to change "Mike's List" to something else, in italic
```

If there is NOT already a "user file" selected, instead looks like this:
```
View
   Flash Call Levels
      [X] Basic
      [ ] MS
      ...
      [ ] C1
      [ ] <I>User file</I> <-- GREYED OUT (also in italic)
      --------
      Select a <I>user file</I> <-- opens the dialog to change "Mike's List" to something else, in italic
```

Something like that, perhaps?....I dunno, @sharmanr what do you think?  I'm OK with what it is now, just thinking that we could tweak it for newer users a bit?

**Comment by sharmanr** [comment]
Yes, I agree -- that's much better!

**Comment by sharmanr** [comment]
Do we need a way of "clearing out" a file if it is no longer needed, perhaps no longer available?  For example,   if "Mike's List" is there but unchecked,  then the users checks it to enable it but we find the file is not longer there -- what do we do?  Leave it there but keep it unchecked?

We can detect the user pressing Cancel on the Select A File option, so we could in this case replace "Mike's List" with "User file"

Also, I wonder if "no file selected" might be better than "User file".

**Comment by mpogue2** [comment]
@sharmanr Good questions.

- Maybe we could copy the specified file into the References folder with a specific name, like "user.<flashCallListName.txt>, so that we have a copy of it (and we still know the name of the list, too)?    We could ensure that there's always exactly one of these by deleting the previous user.* before copying in the new one?  In this way, [ ] Mike's List would always be checkable/uncheckable, once it's been chosen by the user, even if the original file goes away.  I'm also OK with NOT having a "delete user flash file" menu option (just delete it manually from the Resources folder), or a "rename user flash file" (just rename it user.newname.txt, if you want to rename it).
- I like "user file" only because it matches up nicely with "Select a <I>user file</I>".  One points at the other, essentially, so the feature becomes more easily discoverable.  I am agnostic as to whether "user file" or something else works better as the best terminology, but I think they need to match.  Perhaps "no flash file selected" and "Select a flash file"?  Pick one, but they should match, I think.  Maybe just the term "file" is too generic to make it obvious what the feature does?

At some point, making it "nicer" becomes a PITA, though... I think it's up to you, since you may be the primary user of this feature here... :-)

**Comment by sharmanr** [comment]
I've got it working now, in the sense there is a checkable menu item that displays the basename of the filename or "no file specified" and a non-checkable menu item to select a file.

1.  I can't see how to set the filename to be italic.   I tried html-like using angle brackets which didn't work.
I then tried 
   ```
 QFont font = ui->actionFlashCallUserFile->font();
    font.setItalic(true);
    ui->actionFlashCallUserFile->setFont(font);
    ui->actionFlashCallUserFile->setText(menuItemDisplay);
```
but still no italics.

2. Currently there is no way to clear a filename once one is set.  I thought perhaps selecting an empty file would be one way to do so.   There's no real need to remove it really.

**Comment by mpogue2** [comment]
1. Hmmm....docs suggest that menu items can in their entirety be changed to bold or italic, say.  But, they are plain text, and not Rich Text, so we can't italicize part of the string.  Ah well.  Maybe just go with a "greyed out" vs "normal" menu item?  That would indicate that it can't be used, until it's set, and if the text matches, that will be a big clue.
3. Sounds good to me...let's just leave it there then once set.  It is not persistent, right?  So, in this case it will be reset when the app is restarted.

**Comment by sharmanr** [comment]
For 1, I think the enabled property would do it.  I'l check.

Regarding 2, it is persistent.   The reason was to preserve the initial directory for the File Chooser.  I guess I could save just the directory.

**Comment by sharmanr** [comment]
I think if the "user file" is checked then we do want to make the filename persistent,  because all the other levels' checked status are saved so the "user file" checked status should be saved too.  I don't think there's a real harm in keeping the filename after it becomes unchecked; it  just shows that was the last flashcard file used.   (So I think the current situation for point 2 is ok.)

**Comment by mpogue2** [comment]
re: 1 I think that's right -- "enabled" controls greyed out vs not.
re: 2 Yeah, if it retains the directory and the filename itself in a Preference for the next time, that sounds great to me!

**Comment by sharmanr** [comment]
Here's what I have now.  In all cases after the "c3b" line is a menu item that shows the filename if there is one and under that is an item to select a file.
Initially this filename item is greyed out (disabled) and unchecked and shows "No flashcards file selected".
![sd1](https://user-images.githubusercontent.com/76225465/213903683-9fff504a-613b-4c18-a729-398d45bacf72.png)

When "Select a flashcards file" is clicked and a file chosen,  then the filename item shows "File: xxx".  Since the filename wasn't previously checked it remains unchecked:
![sd2](https://user-images.githubusercontent.com/76225465/213903829-fa3c0445-8c74-4d64-b887-07aca53fae4c.png)
That item can be toggled on or off like ordinary levels:
![sd3](https://user-images.githubusercontent.com/76225465/213903990-ad6301aa-942e-4b5a-97d6-3ac2a1223a36.png)

**Note:**
Suppose we exit Square Desk, remove or rename the active file and restart it.   Because the file can no longer be read the filename item is unchecked,  the file displayed as "No user file";  in other words we are back to the initial state.  The directory, however, is retained.
![sd4](https://user-images.githubusercontent.com/76225465/213904056-321870c7-e93c-48b4-803c-33bbf1d3f6b0.png)

When selecting a file, if "Cancel" is pressed, no changes are made, on the assumption that the user changed his/her mind.

**Possibly contentious points:**
1. The checked status doesn't change unless specifically done by the user or the file no longer is readable.   So, for example, ff it is checked on and a different file is selected the new file is displayed and becomes active.

2. Currently only *.txt files are allowed by the dialog and the suffix is removed when displayed, i.e. in the second figure the actual saved filename is 'sooke-ssd.txt".   Should other file types (including all) be accepted?

Comments?

**Comment by mpogue2** [comment]
Couple of comments:
- All looks really good to me!  My comments are minor.
- Might want to 
-- a. put a separator between "No flashcards file selected" and "Select a flashcards file", to better group "no flashcards file select" (or when it changes, "File: spoke-ssd") with the other "levels", OR
-- b. I suppose that it could also be argued that a separator could instead be placed between C3b and "No flashcards file selected", that would group the "user provided flashcards stuff" together, and separate it from the "built-in flashcards level".  
- Personally it feels to me like a. is better, because you're providing an additional "level" to select.  I'm also OK with no separator at all (what you have now).  But, I think it would be an easy thing to add a separator either location.  What do you think?
- Contentious points: 
-- 1. seems reasonable to me.  I suppose we COULD uncheck it, but if the user loaded it, maybe we could argue that they probably want to try it next.  So, I think your choice (to leave it checked) seems very reasonable to me!  
-- 2. I think it would be best to accept any file that you can parse, and reject all others.  So, at this time, unless you want to write parsers for other formats (probably way overkill), I would do what you did, and accept ONLY .txt files, and then remove the .txt suffix (as you did).  Seems quite reasonable to me!

**Comment by sharmanr** [comment]
Ok, added a separator before the "Select a flashcards file".  Otherwise,as described above.
<img width="367" alt="With-Separator" src="https://user-images.githubusercontent.com/76225465/213976757-2edeeb58-aba3-4d80-994c-52814efdabb5.png">

Here's the patch:
[flashcards-file-patch.txt](https://github.com/mpogue2/SquareDesk/files/10477154/flashcards-file-patch.txt)

**Comment by mpogue2** [comment]
Very nice -- code looks good to me, and it worked quite nicely in my testing!  Thanks, @sharmanr!
Do you want to check it?

Commit: e672702a2cbe72d8ccbba82c2b6c3cfd84c3a392

**Comment by sharmanr** [comment]
Yes, it's fine.  Thanks.
