### ISSUE TITLE
Manual: Font is missing

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#787]
Reference/user manual: Please embed the font for the special keys (page 7) to the pdf.
on page 7:
![image](https://user-images.githubusercontent.com/128936259/227743722-1171e5c0-0a1f-4078-a454-25425b35bad7.png)

**Comment by mpogue2** [comment]
Nice catch! I am also thinking about switching to a Wiki for the manual, which would allow other people to help edit it…right now it’s hard to keep that manual doc up to date!

**Comment by mpogue2** [comment]
In the mean time, here is a PDF version of that same 0.9.1 manual that was exported by the latest version of LibreOffice.  It looks like it exported fonts correctly, unlike in the previous version of the document (which was exported by a much older version of OpenOffice).

[SquareDeskManual.0.9.1b.pdf](https://github.com/mpogue2/SquareDesk/files/11073903/SquareDeskManual.0.9.1b.pdf)

**Comment by mpogue2** [comment]
Commit: 1574226ed4da01ed5fd961c1bea228f21f8f8718

Used a more recent version of OpenOffice (I used LibreOffice, actually), and the characters appear correctly now.  I have also started to fill out the [Wiki page](https://github.com/mpogue2/SquareDesk/wiki/SquareDesk-Quick-Reference-Manual), so that this LibreOffice document becomes obsolete eventually.

**Comment by Gero5** [comment]
This version looks good.

**Comment by mpogue2** [comment]
Closing as fixed.
