### ISSUE TITLE
Bug: audio player does not update status line when audio Output device changes

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#788]
Square Desk 0.9.5 on iMac Intel MacOS Ventura

When system setting / audio / output device is changed SquareDesk's audio player does not react to that. The audio output device cannot be changed.

**Comment by mpogue2** [comment]
This is fixed in a later build.

**Comment by Gero5** [comment]
v 1.0.4. same issue

**Comment by Gero5** [comment]
On my Macbook it works with internal speakers and switches to the headphone jack when a cable is connected. 
So I guess it has something to do with the audio Interface an my iMac.
Minor problem.

**Comment by mpogue2** [comment]
Thanks for checking...I'm going to leave this open for now, because there IS a bug here:

**Use case 1:**
- If you plug in a 3.5mm plug into the headphone port, SquareDesk notices that, and switches to it.  The status line updates correctly.
- Similar on unplug.

**Use case 2:**
- If you go to the Sound Preferences panel, and switch from one Output device to another (which is what I think you were trying), then you STOP the SquareDesk music and then press PLAY (OR, press PAUSE/PLAY), SquareDesk will correctly play to the new device, BUT:
- the status line does not update to show the new output device name (as it should have).

So, while the switching function works correctly (next time you press STOP/PLAY or PAUSE/PLAY), the status line doesn't update correctly.

**Comment by Gero5** [comment]
yes use case 2 is exactly how you described. 
but I would expect it to change the output device immediately

**Comment by mpogue2** [comment]
re: I would expect it to change the output device immediately
I'll have to check to see if we are notified of this type of change by the Qt library code.

**Comment by Gero5** [comment]
Just wondering. In my imagination the system event handling should be more or less the same as the event that tells squareDesk that a headphone was connected? In the latter case it changes the output device immediately (1-2 seconds delay) while continuously playing music. (but status line does not change) So all mechanisms are there.

**Comment by mpogue2** [comment]
In theory, you are absolutely correct.  In practice, however, the Qt library sometimes does odd things, and it's often quite painful if we have to dive into the Qt code itself to figure out what it's doing.

So, I need to take a look at what events we're actually getting.  Maybe I'm throwing away events that I could be paying attention to?  Maybe Qt isn't passing events through to me at all, because I didn't ask it to?  Maybe the platforms (Windows and Linux) work differently?  etc.  Until I deep dive on this one, I won't know for sure what's going on, or how difficult it might be to change it.

You're asking all the right questions that a programmer would, though!  Are you a programmer (either employed to code full-time, or do you code in your spare time?). :-)

**Comment by mpogue2** [comment]
Ah.  This appears to be a Qt bug.  Perhaps it will be fixed in future versions of Qt, there's no way to know for sure. 

I already tried to make this use case work in the past, and I left myself a note in the source code:
```
    // Qt BUG:  This function should be called whenever I change the default in the Sound Preferences panel.
    //   However, it actually only changes right now when the devices list itself in the Sound Preferences panel changes.
    //   This happens when I plug or unplug something into the headphone jack, but it does NOT happen when I change the default.
    //   It seems to me that this is a bug.
```

I'm going to leave this open, to see if I can fix the "status line not updating" problem.  But, the "we don't see changes to the Sound Preferences Output panel" might not be something I can fix.

**Comment by mpogue2** [comment]
@Gero5 OK, I looked at this in more detail, and it works correctly every time for me.  Whenever I go to the Sound control panel/preferences, and I change the output device, it is reflected in the status line AND in where music is played, every time.

I am running:
- Ventura 13.3.1 on an M1 Macbook Air
- SquareDesk top-of-tree (commit: df0373)

Once there is a 1.0.5 released, we can have you try it again on your system (some flavor of iMac?).

**Comment by Gero5** [comment]
> re: some flavor of iMac
I am using an
- iMac 2019  27", 3,7 Ghz 6 core Intel i5 , Ventura 13.3.1  at home and 
- MacBook Pro 2017, 3,1 Ghz Intel i5, Ventura 13.3.1 for calling.

I can test it on both.
