### ISSUE TITLE
Feature request: Auto save lyrics

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#796]
I edited lyrics for four singings now and they all disappeared. I admit, that I am the dummy that did not press save. But to me that is not very intuitive and there was no system warning for unsaved changes. Apple users are used to auto saving features on programs like Pages, Numbers, Keynote. Since the lyrics are lightweight html files saving does not cost too much hd bandwidth. I suggest to have one of the following options as a more user friendly and less frustrating behavior of SquareDesk:
 
Prerequisite: SquareDesk detects edits in the lyrics window.
Option a) auto save lyrics to the default name every 10 seconds after editing (or other suitable timeframe)
Option b) auto save edited lyrics when the tab is changed or a new song gets selected

I do not think it is needed but there could be a "auto save lyrics" toggle in the preferences.

**Comment by danlyke** [comment]
The more I use SquareDesk, the more I'm a fan of auto-saving lyrics. It
might be reasonable to, on systems with git, create a git repo in the
cuesheets folder and just commit changes every time we load another cue
sheet or quit. We could eventually expose that in some way, but yes: big
fan of not making me manage save state on my own.

**Comment by mpogue2** [comment]
There are actually a number of reasons why editing lyrics/cuesheets is modal (Unlock to edit, Save to end editing), and similar reasons apply to the SD changes that I just made (which is why editing on the SD page is also modal).  Here are a couple of those reasons:

- As you already mentioned, I find personally that it is really easy to make unintended changes to cuesheets, while at a dance.  The modal "edit/unlocked" mode makes those mistakes go away.
- Some features, like "auto-scroll cuesheet" are actually modal -- they happen in View mode, but not in Edit mode.
- Keys need to have different meaning when editing and when viewing (e.g. using a cuesheet at a dance).  So, the "P", "spacebar", "period", and arrow keys, for example, all have different effects in edit mode vs view mode.  
- Many of the key assignments were done to match SquareView, which almost all callers are familiar with, but there is a bigger issue here that "keys needed for editing are also needed to do transport control and other music functions".  This is because you can be playing back music while viewing or editing a cuesheet.  (Similar for the latest SD changes -- I need to be able to View sequences, without danger of editing them, while playing music at the same time).
- The Lyrics editor is actually not a full-blown general-purpose HTML editor for SquareView-style arbitrary HTML cuesheets.  It intentionally rewrites cuesheet files to be:  
-- human readable in a canonical format
-- self-contained (no dependence on cuesheet2.css, so that cuesheets can be sent to friends who don't use SquareDesk or SquareView), 
-- machine-readable (semantics, not presentation), and 
-- minimal (it deletes all of the MS-Word-to-HTML cruft that MS inserts to make a cuesheet 10X bigger than it needs to be).  
    That transformation is done at Save time (only), and so I don't think that would work well with an auto-save model.

Regarding the "auto-save" approach:
- If SquareDesk were just a Lyrics Editor, then I think the "auto-save model" might be a viable option to consider.  But, because SquareDesk is a music player, a cuesheet editor, a sequence viewer, a sequence editor, et.al., we will probably need to have some features that are modal.  I think that unlock/lock is the simplest approach that addresses all the use cases.
- There are very few applications in the Apple ecosystem that use Apple's recommended "auto-save" approach (e.g. File > Browse All Versions), despite their pushing it for many years.  I have just one app (of 100 apps) that uses it, and it's a pain in the ass to use (e.g. no, I don't want to duplicate the current file and then rename it and then move it manually, I want to save it with a different name in a different place).
- There are much simpler and more powerful alternatives to building git into SquareDesk. :-)
-- All of the major cross-platform Cloud Storage providers maintain "version history".  Many of them are free (up to a certain amount of storage space, a lot more than the lyrics folder takes up).  I primarily use Box.Net nowadays, since it works better with SquareDesk than the others, but any of them will work.
-- Local backup solutions provide essentially infinite version history, too.  I use Time Machine on Mac, but there are many solutions in this space, designed to meet different needs.
-- If you really want to use git, you can still use it from command line (or GUI -- GitKraken is my fav).  We have users who don't know git at all.  So, it's not just "save a version" that we'd need to support, it's some way to "view all the versions" and "restore a version".  


So, bottom line (I know this is a long post, but I thought it would be good to document some of these design choices): I think that unlock/lock is not perfect, but it is fairly simple and approachable for a combination app like SquareDesk.

On the other hand: :-)
But, let me also say that if you really want a solution that will work on your system (where you've installed git yourself), and you only really care about "commit a new version" (doing all the other stuff using git command line or GitKraken), we could provide a hidden and lightweight hook just for that (and this would be pretty straightforward, I would think).

Something like this:  Whenever a cue sheet is loaded, it shells out to a script called "commit_lyrics.sh" (if that file exists).  That file could contain some git commands to commit all new and edited files (or whatever you prefer -- you're a power user, so you can customize it).  That way, it would essentially not impact the non-power users, but I think it would give you the "automatic git commit" that you're looking for.

**Comment by Gero5** [comment]
I would like to re-enhance this. 
Following use case: 
- a singing call is selected, cue sheet page is shown, user clicks 'unlock to edit'
- user adds some edits to the lyrics/cuesheet
- user clicks 'Music Player' and selects another music file
--> all edits in the cue sheet get lost

this happens very frequently to me and, sorry, I am not learning.
I think a more user friendly handling of the use case can be found. At least a warning box with save-button saying that the changes in the cue sheet get lost without saving. Auto Save in this case is still my personal favorite.

after reading the long post of @mpogue2 above again I do not understand why we cannot have a save option within the modal design of the cue sheet editor. Keep the 'unlock' button as it is and save the changes before the user selects another piece of music. Lock the cue sheet file. Done.
or at least let a warning pop up as mentioned above.

**Comment by mpogue2** [comment]
@Gero5 Thanks for the details!

I think this is the same issue as #765, which is also related to #887 (need a revert button, not just a menu item)

I am inclined to do the following:

**UNLOCK button** = opens for editing (as today)
**SAVE, SAVE AS... buttons**  = saves, and closes for editing (as today)
**REVERT button** = add a new button to revert edits (makes this more findable)
**add menu items**: Cuesheet > Unlock, Cuesheet > Save, Cuesheet > Save As (Cuesheet > Revert edits is already there), (makes these findable a second, consistent way)

**User selects a new music file while cuesheet is unlocked** = add a dialog asking if you want to SAVE/DON'T SAVE
(Note: I prefer this way, because at least one user intentionally uses this use case as an escape to revert changes -- they can click on DON'T SAVE in the new way, if they want to revert)

**User tries to close app while cuesheet is unlocked** = add a dialog asking if you want to SAVE/DON'T SAVE/CANCEL

**Comment by Gero5** [comment]
Reads good to me.

Mike Pogue ***@***.***> schrieb am Mi., 23. Aug. 2023, 02:22:

**Comment by mpogue2** [comment]
OK, the "user selects a new music file while cuesheet is unlocked" is fixed by 246014ef2b2c64c86764b9753f0b2cd057abc0f8 .

At this point, I think all the pieces for this one are in, so marking it ready for final check.

If the cuesheet is unlocked, the cuesheet selector is now DISABLED, so that the user can't switch to a different cuesheet in the middle of editing (this is the simplest approach).  Also, if the user double-clicks to load a new music file, the user will now be asked to Save, Don't Save, or Cancel.  Save will save and then complete the load. Don't Save will NOT save and then complete the load.  Cancel will not save AND will not load the new song.

**Comment by mpogue2** [comment]
The QUIT use cases are addressed by: 9218892740f621271e3294f30ccb11c8e51c577f

The QUIT use cases are now tested as well:
- Unlock, then QUIT, then SAVE.
- Unlock, then QUIT, then DON'T SAVE.
- Unlock, then QUIT, then CANCEL.

If a cuesheet is being edited, and user QUITs, they will get the usual SAVE, DON'T SAVE, CANCEL dialog.  SAVE will save and quit.  DON'T SAVE will not save, and will quit.  CANCEL will abort the Quit entirely (and leave the cuesheet open for continued editing).
