### ISSUE TITLE
Feature: Proposal for a cool looking gui

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#805]
I fumbled a little bit with design elements for a cool looking gui that could make Mac users happy and windows users jealous. :-)

I put it in dark mode because I personally think it looks cooler and it made it a little easier for me to put the elements together but it would work in light mode as well.

![Bildschirm­foto 2023-03-29 um 13 56 34](https://user-images.githubusercontent.com/128936259/228528523-9b7b3bc4-5c5b-4912-9cc3-717ffa15aa86.jpg)

![Bildschirm­foto 2023-03-29 um 17 07 23](https://user-images.githubusercontent.com/128936259/228583506-da064522-99cf-4362-abac-12ccd1ad2882.jpg)

**over all view**

- Aims to be clear and tidy
- Slider for Volume, Mix, Tempo aso. are made with thinner lines and rectangle (mixer knob) at the current position.
- Color gradients instead of solid colors
- Avenir New is used as font fro a modern look

**Audio presentation:**

- Song is shown as a mini waveform.
- A red line shows the current play position accurately.
- decent coloring for the parts of a singing call.
- Only the slider for Tempo remains underneath
- One frame for all text informations for the song, using harmonic font sizes and colors 
- Time can be clicked to toggle between time played and time remaining
- Loop start and loop end have markers that you can klick and draw with the mouse

**Control Buttons Play, Stop aso:**
- New modern look
- Color gradients
- VU and Volume grouped together on the left

**EQ, Pitch, Mix** 
- grouped together on right
- these informations are saved for a given audio file
- Things that are not touched during a dance/clubnight very often

**Loop Editor for patter audio** 
- EQ-Field can be replaced by the loop editor so it does not need extra room
- loop editing moves from the lyrics tab that has nothing to do with looping

**What else?**
- New look for the clock

Here is the look of the audio player for patter music:
![Bildschirm­foto 2023-03-29 um 14 27 55](https://user-images.githubusercontent.com/128936259/228535273-857b5d89-2825-4bf9-834d-3599682c184e.jpg)

**Comment by mpogue2** [comment]
Very nice!

Can the Light view be derived algorithmically from the Dark view (or vise versa?)

**Comment by Gero5** [comment]
re: Can the Light view be derived algorithmically from the Dark view (or vise versa?)

You can have it that way. Except for VU meter and the waveform you can simply invert all colors. Result looks like that:
![image](https://user-images.githubusercontent.com/128936259/228878449-7fa57029-f1dd-4313-b9cc-7a37704a7b97.png)
This is not too bad for just inverted colors. I think "Figure 3" should have a color close to red, the mixer and the clock need little color adjustments. But that is only because I copied pictures that weren't really matched to the dark mode colors. remember it this just a design sketch. 

I personally like the color gradient better from light on the top to a darker color below. light from above. It is, after all, the direction from which we have expected light to come since the dawn of time. :-)

So with a few adjustments it looks like this:
![Bildschirm­foto 2023-03-30 um 18 28 37](https://user-images.githubusercontent.com/128936259/228903144-f2aab0c7-a84d-4b6b-b969-7a1136229d47.jpg)

But I think we are far into details. Which one do you like?

**Comment by mpogue2** [comment]
I personally like the "light" mode better, but that's just a personal preference.  I know a lot of people like "dark" mode.

Overall, I really like the design.  It addresses some of the UX ideas we've had in the past, and it addresses them way better than we've looked at in the past:

- #79 Waveform display
- #611 Update the UI

One of the big challenges here will be to get Qt components that have the professional look and feel that you've shown here in your mockups.  My thinking is that we'd need to reuse components from another project, and Mixxx is probably the best candidate.  It's open source, uses a very similar aesthetic, and works with Qt (which we also use for GUI building).

Although Mixxx is quite mature as an project, it has some limitations:

- it has its own build system that is completely different from the one we use.  It's not clear how easy it would be to grab components from Mixxx and reuse them.
- Mixxx consumes 60% of a CPU on my M1 (and that's using their [M1-optimized version](https://github.com/fwcd/m1xxx/releases)).  So, CPU consumption is about 5-10X what we are using now.   I suspect that's in large part due to their heavy use of graphics, even though their components do leverage the GPU (which offloads the CPU).  I don't think we'd be able to do much better than that CPU-wise, so there is a price to pay for all the nice realtime waveform graphics.

If you haven't checked out [Mixxx](https://mixxx.org) yet, you should!  If you're only looking for a music player (no lyrics, no SD, etc), it does a lot of what SquareDesk does, it's free, and it does look very cool.

**Comment by Gero5** [comment]
Well, my first thought: 60 % of CPU is not worth the price for just a better look. 
But I do not think that that is really needed. In mockup I am using simple forms like lines, rectangles, triangles and circles. That is all. The waveform only is an object that is more on the complex side. The color gradients add the more professional impression. There must be a framework out there that allow simple forms with color gradients.

I do not know anything about qt... but my google search found that it allows to use some kind of [style sheets](https://doc.qt.io/qt-5/stylesheet.html) for 'qtWidgets'. And color gradients can be defined.
[Qt Graphical Effect LinearGradient](https://doc.qt.io/qt-5/qml-qtgraphicaleffects-lineargradient.html)
If we can add this QML type to the graphical elements of the gui then there would be hope. I do not have time to dive deeper into at the moment. Probably you could tell right away if this possible or far away from a promising approach.

**Comment by mpogue2** [comment]
Also note that if we can extract some of the controls from Mixxx, that makes some of these much simpler (e.g. the Mixxx sliders are really nicely done!).  But, that extraction might be challenging.

**Comment by mpogue2** [comment]
I'm also OK with making incremental changes toward this nicer GUI design.  (I can #ifdef many or most of these, so we can always easily go back to the current way, if needed.)

**Font example:**

Adding this code to main.cpp changes the font used for everything in the app.

```
    QFont font("Avenir Next");
    QApplication::setFont(font);
```

And, the result looks like this:

![image](https://user-images.githubusercontent.com/6316003/228993685-ea3480dd-de71-461c-b262-8da1cd1b6e7c.png)

Comparing that to the current font we use:

![image](https://user-images.githubusercontent.com/6316003/228993885-b7160581-21bd-485a-87db-a02e0dbd823d.png)

**Comment by mpogue2** [comment]
A couple more comments, in random order:

- I actually like the frame around the status stuff in your "Basic Ideas" view.  I think it sets off that section visually, making it easier to read.
- Due to the way Qt works, UI controls cannot be placed above the line established by the **bottom** of the tab control.  So, VU meter and clock need to be moved down below that line (you can see this line in the two screenshots immediately above this post).

**Comment by Gero5** [comment]
re: I actually like the frame around the status stuff
I thought about that too
re: Due to the way Qt works, UI controls cannot be placed above the line established by the bottom of the tab control.
So we need a little extra space above. It looks like this:
![Bildschirm­foto 2023-03-31 um 09 20 48](https://user-images.githubusercontent.com/128936259/229051505-72c390e1-643d-49b0-81c9-67ebdf08cbfe.jpg)

re:Loop editor is also needed for intro/outro points in a singing call. 
Don't get it.

re:EQ is probably needed for Patter from time to time.
The idea was that you can close the loop editor with button at the bottom. EQ is displayed.

re: Volume is actually not used that often. maybe it could go to the same place that the EQ controls went
If it is saved for the specific song that is far better. But we have to be aware of the fact that space is limited.

re: Avenir Next takes up more vertical room than the default font. 
I would say that is because it is another font. (Sorry...)
Try google Font Montserrat as an alternative. Can we use one font for the display and the Standard Font for tab buttons, list aso. (which I would prefer) or is it one font for everything?

**Comment by mpogue2** [comment]
re:Loop editor is also needed for intro/outro points in a singing call.
On the Lyrics tab, the In and Out buttons are used to set precisely where the OPENING starts, and the CLOSER ends (respectively).  Doing so makes the label accurately transition in time from OPENER --> FIGURE 1 --> FIGURE 2 --> etc.

re:EQ is probably needed for Patter from time to time.
Ah, I didn't see that button!  Would there be a way to get EQ back?

re: Can we use one font for the display and the Standard Font for tab buttons, list aso. (which I would prefer) or is it one font for everything?
We can set a separate font for each separate widget, each separate widget type, or everything at once.  I think my preference would be to avoid mixing fonts, especially if one of those is the default font.  But, we have definitely have options here.  It looks like it's possible to embed a font into SquareDesk.  When I get a chance, I'll see what Montserrat looks like!

I'm also wondering whether there's some "margin" that I can set on the table cells, or some property on the font itself, that would force it to not use up so much vertical space.

**Comment by mpogue2** [comment]
More info:

```
    QFont font1 = QApplication::font();
    QFontMetrics fm1(font1);
    qDebug() << "metrics:" << fm1.height() << fm1.leading() << fm1.boundingRect("THIS IS A TEST.");

    QFont font2("Avenir Next");
    QFontMetrics fm2(font2);
    qDebug() << "metrics:" << fm2.height() << fm2.leading() << fm2.boundingRect("THIS IS A TEST.");
```
returns:

```
metrics: 16 0 QRect(0,-13 93x15)
metrics: 16 0 QRect(0,-12 80x16)
```

So, it does appear that Avenir Next strings are substantially narrower, and a bit taller (unexpected for me) compared to the default font. 

We might compensate just by choosing a correspondingly smaller point size?  I actually like the fact that horizontally the Avenir Next string uses many fewer pixels.  That might give us better readability for longer song titles.

**Comment by Gero5** [comment]
font: In theory you are right. a font of size 16pt should have the same height. But then there is the Didot-point system and the Pica point system and both have slightly different sizes. 

re: We might compensate just by choosing a correspondingly smaller point size? 
Give it try and see how it looks. Can you make a screenshot with an auto title displayed also?

Yes, Avenir Next takes more space for the same words. Note that is copyrighted font. So please check wether it is available on Linux systems as well.

**Comment by Gero5** [comment]
re:Loop editor is also needed for intro/outro points in a singing call.
Now I understand. I have not realized it before. Is there really much demand for this? for me the default worked quite well.

Any way if we replace the clock by a pure digital clock this will give us some space. the loop/position editor can go the left h side when we move the VU meter. The "Test Loop" button dissaperars on singing audios. The clock/VU and position editor could also trade left/right places but then there would be  two time counters close together wich I do not like.
![Bildschirm­foto 2023-03-31 um 13 59 49](https://user-images.githubusercontent.com/128936259/229114705-67821a8a-1343-4244-ab56-c9aee7089bc1.jpg)

**Comment by kevinmcdaniel** [comment]
re:Loop editor
Yes there is demand for controlling when the loop starts and stops.  There are many new sources of music that don't conform to "standard square dance" length and timing.  Being able to control the loop timing and having it saved with the song data for recall with eq values, tempo and volume.

**Comment by kevinmcdaniel** [comment]
Got it.  I've not used the lyrics in 0.9.5 to any extent yet and have not modified the intro/outro timings.  Thanks.

**Comment by mpogue2** [comment]
@Gero5 Here are two screenshots, with text in the song title field:

Default font:

![image](https://user-images.githubusercontent.com/6316003/229242589-9cff8526-94f8-4208-acfd-f058a3217055.png)

Avenir Next:

![image](https://user-images.githubusercontent.com/6316003/229242654-df1a20fc-8baf-4f7d-9b2c-e6639e4a8dc2.png)

**Comment by mpogue2** [comment]
Ah, I learned something today!  I can style the buttons for both gradient AND rounded corners at the same time using stylesheets:

```
    QString toolButtonGradient("QToolButton{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #F0F0F0, stop: 1 #A0A0A0);border-style: solid;border-color: #909090;border-width: 2px;border-radius: 8px;}");

    ui->previousSongButton->setStyleSheet(toolButtonGradient);
    ui->nextSongButton->setStyleSheet(toolButtonGradient);
    ui->playButton->setStyleSheet(toolButtonGradient);
    ui->stopButton->setStyleSheet(toolButtonGradient);
```

gives us this in context (this is just a quick test, so button spacing is not changed here):

![image](https://user-images.githubusercontent.com/6316003/229246976-3a3a5639-f6df-4c82-b0f3-4c3c54602d49.png)


@Gero5 Gradients should be top to bottom -- or were you looking to use upper left to lower right instead?

**Comment by Gero5** [comment]
Gradients: In the mockup I used top to bottom for 
- general background
- song information field
- mixer background
- loop editor background
- loop editor buttons

diagonal gradients for
- play, stop, prev, next buttons backgrounds
- inner elements of the buttons like square, triangle...
- slider knobs rectangles

**Comment by mpogue2** [comment]
@Gero5 re: digital clock -- check out the "Clock Coloring" feature.  I use it all the time at my dances...
Turn it on in SquareDesk Preferences > Experimental (although it's been there for 5 years, and is really not experimental any more!), then play some patter music.  A couple mins later, play a singing call.  The coloring around the outside edge matches the selected colors for patter and singing call in Preferences.  Super useful for break timing, and knowing whether tips are starting/ending on time or not.

![image](https://user-images.githubusercontent.com/6316003/229251321-fd93f918-4e82-441f-9fd9-ddfbe166127b.png)

**Comment by mpogue2** [comment]
Here's a partial view of the Mixxx default skin:

![image](https://github.com/mpogue2/SquareDesk/assets/6316003/ef304a47-dc4e-45bc-b685-bcacf60bf224)

What I like:
- layout is similar to Gero's in many ways
- a lot more compact than what we have now
- round small knobs for B/M/T (they call L/M/H)
- volume is a vertical slider
- pre-gain control (the red-lined small knob above the volume control) to avoid clipping
- Clicking on the time-in-song toggles between time-in-song, time-remaining, and both
- Tabs are just buttons in the upper left
- Can't see in this screenshot, but the columns are all toggle able by right-click on the header, AND they are reorder able
- The left hand side has Crates, which are basically playlists.  You can drag/drop a song to a crate, OR right-click > Crate > Crate Name to add to a crate.
- Waveform display is nice.
- The way they did loop start/end is pretty simple (right pointing arrow = start loop, left pointing arrow= end loop, both pointing arrows = loop enable)
- can specify multiple music dirs in preferences

What I'm not sure about:
- single Search... field filters all fields, e.g. cappella will be the query artist contains "cappella" OR title contains "cappella"
- but, the search... field can have prefixes, e.g. "artist:foo title:bar" will be the query artist contains foo AND title contains bar

What I don't like:
- SO many controls (we need something much simpler)
- No easy way to make the text easier to read (have to scale the whole app and restart it)
- Can't independently adjust tempo and pitch (we'd want two sliders or two knobs, I think)
- Clock is way too small and digital only (I like our clock coloring, which I use all the time)

**Comment by mpogue2** [comment]
I've got a couple of dark mode widgets working in a separate Qt sandbox now, that are based on the look and feel of the Mixxx widgets (which I like).  I'm using "Avenir Next" as the font for the song title and time-in-song. The widgets look like this (shown with tooltip that appears when hovering over the midrange knob):

![image](https://github.com/mpogue2/SquareDesk/assets/6316003/b9834e48-9b90-40af-8040-df180123bb50)

Next step is to stick these into SquareDesk (in an experimental dark mode tab, I think), and start playing around with the exact arrangement of the controls using the QtDesigner (doing this layout stuff with code is quite painful).  I'm not going to tackle the waveform display quite yet (it's quite a bit more difficult than these dials and sliders, I think), so I'll probably just stick in a regular horizontal slider with brackets for the loop points for now, and update it later.

The looks for these new knobs and sliders are based on a couple of Mixxx SVG files, that are editable using Inkscape.  (I'm following the general design language, not always the exact pixels).

The other components needed for an initial layout, like dark mode buttons, are pretty straightforward. I still need to think some more about best to do dark mode VU meter and clock components.  I can probably do those pretty much the same way as the knob and slider components (using a QGraphicsScene).

**Comment by mpogue2** [comment]
TODO:
- move svgDial into SquareDesk source code base [DONE]
- move svgSlider into SquareDesk source code base
- prototype some layouts for Dark Mode (new Music tab layout) [IN PROGRESS]

Current state of the prototype layout:

![image](https://github.com/mpogue2/SquareDesk/assets/6316003/2c8549bb-d36b-4926-93de-4fa30fa86dfa)

NOTES:
- This prototype is partially functional.  The widgets are all real, and you can interact with them (poke around, move the knobs, highlight items in the table, etc.), but nothing is really connected to anything.  So, can't play music, etc.  It's just for prototyping the look and feel right now.
- DARKMODE tab is only visible if the DARKMODE compile flag is turned on.  The code is there, but only developers can play with Dark Mode.
- I don't have sliders, clock, or VU meter in yet.
- The tabs will be replaced with buttons that do the same thing (but are more compact, a la Mixxx)
- Many of the colors are not correct.
- The songTable rows are too tall right now, and the songTable is not zebra-striped yet.
- The tree view implies some new functionality:  click on a playlist, and it (and only it) appears in the songTable.  Similar for history, iTunes (play from your iTunes library).  Tracks does type filtering.
- I'm thinking about the Mixxx-style search box, rather than separate search boxes for each column in the songTable.  It's a placeholder for that idea.
- I am thinking that the current Music tab and this new Dark Mode Music tab could co-exist (at least for a while).  This would avoid Light/Dark Mode switching on-the-fly, and would (temporarily) give ustime to see how we like the new layout, before obsoleting the old one.

**Comment by mpogue2** [comment]
OK, here's where I am on the look-and-feel prototype.  The controls are all live, but there is nothing being controlled behind the UI right now.

![image](https://github.com/mpogue2/SquareDesk/assets/6316003/9d64ff2d-12ba-4762-a6dd-74940ef02f22)

**TODO:**
- Put the MIX control in somewhere (knob?  or should we just assume this will be done on an external mixer from here on in?  I think I have 2 songs that have split-track, and I never use the split-track feature on those two songs either...)
- column visibility control (Mixxx does Right Click on songTable header and a popup menu).  Are there other ID3 tags used by music producers, that could become columns here?
- Put the warning label in somewhere ("LONG TIP" or time-in-tip or "OPENER/etc.").  Where should this go?
- make the clock round instead of square (using transparency), add in prototype clock coloring (which I use a lot)
- make a Waveform control using QGraphicsScene (patter: white waveform, singing: waveform is colored).  I am hoping that updating it once per second will use less CPU time.
- replace the tab controls (coming from Fusion, as is the spurious menu bar control thing) with small ALLCAPS buttons, like Mixxx).  Right now these are too big -- they need to fade into the background a bit (do I have to replace Fusion to do this?)
- attach tooltips to the new controls that don't have them yet
- the clock is just a PNG right now.  I am hoping to reimplement using QGraphicsScene, and reduce CPU utilization further... I think this might avoid the update() calls that happen 1/sec that are fairly costly.  We're NOT calling repaint() either right now in Dark Mode.
- Drag and drop from songTable to playlists.  Drag and Drop for reordering playlists.

**Comment by mpogue2** [comment]
**NEW:**
- Changed some text colors to white (the yellowish color Mixx uses for text is too yellow for my taste)...I might change the other ones too...
- added pitch slider
- clock is now live (second hand can be turned on/off at compile time, now shows digital time as well).  It is implemented using QGraphicsScene.  The new clock uses about 0.3% CPU (note: the main clock on the Music page is still running.)
- connected the sliders to their labels, so the labels change automatically as you move the slider knobs

**TODO:**
- clock should move when realtime seconds gets to zero (reimplement clockTimer as a one-shot, with time = seconds to get to next minute + 1)

**Comment by mpogue2** [comment]
Changed:
- VU Meter is now live.  It updates 10X/sec and it uses an almost unmeasurable amount of CPU time.  I also made it so that if the Music tab is showing, only the regular levelMeter is driven, but if the DarkMode tab is showing, only the darkVUmeter is driven.  So, we're not using double CPU.  (Eventually this will not matter, as the DarkMode tab will replace the Music tab...)

![image](https://github.com/mpogue2/SquareDesk/assets/6316003/65c0502d-bfe5-4e24-b6c0-96756cb3862c)

**Comment by mpogue2** [comment]
Buttons hooked up [DONE]:
- Stop
- Play/Pause
- Loop Start/End
- Test Loop

Labels hooked up [DONE]:
- Song Title
- Time in Track
- Song Duration

These controls still need to be hooked up (bidirectionally):
- seekBar (SVGmusicWaveform control in DarkMode)
- T/M/B EQ controls
- Volume
- Tempo
- Pitch
- Start/End Loop Times
- SongTable (and context menu)
- Clock: Coloring
- Clock: context menu

New control that needs to be hooked up for the first time:
- TreeView

**Comment by mpogue2** [comment]
BUG: All mySliders seem broken, when trying to click in the vein to move the slider to THAT position, it moves as if it's a Page Forward/Backward instead of a Jump To This Point.

**Comment by mpogue2** [comment]
TODO: Loop controls disabled until song is loaded.

**Comment by mpogue2** [comment]
I tweaked the purple color, to have the same S and V, and just change H (using HSV, then converting to RGB Hex).  I think this is better:

![image](https://github.com/mpogue2/SquareDesk/assets/6316003/e86781c9-4506-4846-9b52-702d592d08a7)

**Comment by mpogue2** [comment]
Note to self: should probably horizontally center the digital time in the clock.  It was centered when the hour was hh, but it's not centered now that the hour is just h.

**Comment by mpogue2** [comment]
Commit 3c614d4d66389018afd09fba86b107e5c3ace6e3 .

Introduces new controls based on some SVG assets from Mixxx (open source).  Follows the general UI look and feel of Mixxx.  Some controls are hooked up, but many are still mockups (live, and you can play with them, but not really hooked up internally).  Useful for trying out layout ideas.  See screenshots in #805 for pics without having to build it yourself.  To turn on the Dark Mode tab, uncomment line 216 in mainwindow.h .  If the Dark Mode tab is not enabled, SquareDesk should see no changes to the normal GUI.

**Comment by Gero5** [comment]
I appreciate that this gets some progress now. Thank you for the effort.
my comments:

What I like:

- the font for the title looks cooler
- knobs an sliders look much more professional
- I like the tracing on the sliders and perimeter on the knobs. 
- reduced design of the clock
- loop values on the music player surface

suggestions/stimuli (of course all a matter of personal taste):

- The look could be a bit more balanced design-wise. 
- The many colors make it more confusing than helpful to me.
- For my personal design guts feeling I would choose less colors to make it look more high grade. I would choose some light grey for square and triangle on the play/stop-buttons, tempo/balance/pitch/vol-sliders and EQ-knobs instead of red/green /blue and maybe reduce colors on the clock. And a darker grey for the horizontal line under the song title instead of red.
- I like the tracing on the sliders and perimeter on the knobs. Would work with greyscale as well.
- EQ knobs: I personally prefer sliders over knobs, because when I try to adjust knobs with the mouse knobs always turn in another direction than I thought they would. But maybe I can find somebody grown up that can explain to me how that works. ;-)
- the values for tempo/pitch (I guess) and volume as well as T/M/B could be a bit darker in the greyscale to lift off the music values from these adjustments. 
- the values for tempo/pitch (I guess) and volume should have the same (smaller) font size as T/M/B
- I also thought if we could put adjustments elements in a different design that are not used during a running dance. The advantage would be to keep the surface nice and clean and do not overload it with things that are not needed when running a dance. However different users may have other options than me on the following.
For me EQ, pitch, balance and even song volume are one time decisions that are done in prep time before a dance. There could be a single button for that - either for all or one for EQ and on for the other song adjustments) on the surface. The button is high lighted when changes are done to the defaults values. When the button is clicked a pop up window appears and give the possibility to change the values with sliders or knobs.
- shouldn't there be a square around the clock if everything else has a rectangle around it? I have not made my mind up jet wether I like it better without any rectangles.

**Comment by mpogue2** [comment]
@gero thanks for the comments!  A couple of responses:

- Look more balanced: This is a prototype, and I've designed it to be able to be live (so it can be tested in real usage), but also to make it easier to experiment with layout.  Stay tuned... :-)
- Less colors:  I agree!  This prototype was to see if I could reuse the Mixxx colors.  I think the knobs, in particular should be more monochromatic, like the Mixxx counterparts.  The coloring of the patter vs singer is already under user control in the Preferences control panel (it can be set to shades of gray, or anything else you prefer).  I was experimenting with the Pitch slider being a different color than the Tempo and Volume sliders.  Mixxx actually uses the same color for all the slider handles.  I'll try that next.
- knobs:  I think you will like these knobs better than the default knob implementation.  Try out Mixxx, if you want to get a feel for these (my implementation is nearly identical).  It's NOT a circular motion to move the knobs, it's either up/down or left/right (or both).  Much easier to use.
- Values for Tempo/Pitch/Volume/T/M/B:  please suggest some color here for the text?  
- Text size goes, I was following the Mixxx style here, where the labels are smaller than the values.
- Hiding adjustments: Maybe a possibility, but I do tend to adjust during the dance.  I'll have to try this out, and see how it works in practice.  Mixxx uses buttons to turn on/off various panels.  We might do the same.  I haven't implemented those Mixxx-like buttons yet.
- Clock square:  I also wasn't sure which way I liked it!  I'll try with the square, and let's see what it looks like.

My goal right now is to finish wiring up the dark mode controls (so everything actually works), and let users actually try it in practice (and I am doing the same!).  It's a separate tab, so you can switch back and forth between the old style and the new style (although I don't have switching between Dark and Light mode yet, so the Old style is also a weird semi-dark mode right now...).

Thanks again!

**Comment by mpogue2** [comment]
TODO: VU meter reading is lower than old VU meter

**Comment by Gero5** [comment]
> Values for Tempo/Pitch/Volume/T/M/B: please suggest some color here for the text?

Use a light grey instead of white. Maybe the same color as the numbers 12/3/6/9 on the clock dial to get not too many variations.

**Comment by mpogue2** [comment]
Commit: 9cccfda73a215c9a88468ddcc01eb3db8ce366a2

- EQ Knobs are monochromatic now
- Fixed coloring of flash calls
- STOP and PLAY buttons are now color-selectable (in code), and are now a lighter gray
- Volume sliders are ganged together now (changing one will change the other too)

**Comment by mpogue2** [comment]
TODO: dark VU meter flashes at startup

**Comment by mpogue2** [comment]
Commit: 2b0d469560660da0ba908adedbd52a692c4f193a

Dark Tempo and Pitch sliders now hooked up.  Dark EQ knobs (T/M/B) now hooked up.  Made some minor color changes, including the change to a light gray as per suggestion above.

**Comment by mpogue2** [comment]
TODO:

- dark sliders should probably be disabled until a song is actually loaded
- loop time boxes are not hooked up yet.  I wonder if I will ever use them, given that the beat/measure detection is working so well now!?
- dark waveform display is just an image right now
- dark songTable is just an image right now
- replace tabs with Mixxx-style buttons
- dark VU meter flashes when I switch to the DarkMode tab
- Elvira has a glitch at the beginning that shows up in the VU meter momentarily
- In Mixxx, the line under the title is actually colored from the "Color" field of a song.  We don't have that.  Should we?  Or, should we color it with patter/singer colors to indicate in a subtle way what type is loaded?
- TreeView is just a placeholder right now
- Search functionality like Mixxx should be interesting to write (and TreeView selection can in many cases just set the search field? and does it also change the view, or do playlists continue to use the # field?)

**Comment by mpogue2** [comment]
Loop controls hooked up now, except the loop time displays are editable (but editing them does nothing -- they are only displaying the loop times).

Current look, after the above changes:

![image](https://github.com/mpogue2/SquareDesk/assets/6316003/3436a5f8-8eda-4781-b6b5-00eedba548b4)

**Comment by mpogue2** [comment]
Feature to fix Elvira: A way to set "song start", similar to "start loop", but the Cmd-. always goes back to the songStart position rather than 0.0 .  I always hate it when I have to wait 5 seconds after PLAY to start hearing sound.  This happens on just a couple of songs though.

**Comment by Gero5** [comment]
suggestions/stimuli:
- use the same greyscale as on the knobs for the vertical sliders (+/-/horizontal line on the sliders) to have a consistent match for all controllers
- clock: (admittedly I am getting a bit picky...) Can the digital time be in a greyscale? fingers: if you want to have the fingers in color I would prefer a pastel light yellow over the white/red.  if it needs a highlighted finger at all the long finger would be my first choice because that is the important indicator for me during a dance. Usually I know the hour.

> loop time boxes are not hooked up yet. I wonder if I will ever use them, given that the beat/measure detection is working so well now!?

Nice if it does. So far I am adjusting the loop times for all of my patter music. Note that 80 % of the music I use for patter calls are not square dance productions but "normal" radio dance hits or EDM. Some of them have a long intro that I do not want to include in the loop. I do not think that this can be detected automatically. So I need to set individual loop times, please do not kill that.
example:  - loop starts at 0:41:353 
[https://www.youtube.com/watch?v=VuGQnP8ur6M](https://www.youtube.com/watch?v=VuGQnP8ur6M)

**Comment by mpogue2** [comment]
Comments:
- colors in general:  I am trying to generally follow the Mixxx style, which I think is pretty well-designed.  But, I also think it might be good to create a way for users to customize colors, because we are not going to 100% agree on everything...  The knob designs are in SVG files, for example, accessible to the user, so although it's not trivially easy for ALL users to do so, I think somebody like you could do it pretty easily.  Let me think about how best to do that, especially for the colors that are not in SVG files....  

- Loop times:  I think there are two questions here:  a) retain the spin boxes for times?  I think. you would say "yes", even though adjusting them by clicking the "[" or "]" buttons might be simpler for most.  b) the "long intro" problem, which is the case with the song "Elvira", which has 5 seconds of silence at the start.  In this use case, I'm considering ADDING a control, for a total of 3:  song start (new), loop start (existing), loop end (existing).   I think with your Mozart song (which I really like BTW!) would put the song start to 41.353, and the loop start could be sometime AFTER that point.

**Comment by mpogue2** [comment]
Commit: 2c982fe431c2914245632cf2b9a3e0c678e12ff0

Minor updates to colors for consistency, including the clock hands (will likely make this user-selectable later).  Enabled dark loop controls same as original loop controls on the Cuesheet tab. Added "#" column back in, as per original songTable.

**Comment by Gero5** [comment]
**Loop Times**
> a) retain the spin boxes for times? I think. you would say "yes"

YES, I do say yes. I need the hundredths of a second to adjust the the times. I am very picky that the loop jumps exactly on beat measurements and the jump is unheard by the dancers.

>b) the "long intro" problem, which is the case with the song "Elvira"
Uh, I did not understand what the "Elvira" problem was a bout so far. If it is really 5 seconds of silence (0dB)  without noise an automatic detection

**Comment by Gero5** [comment]
**colors in general**

> I am trying to generally follow the Mixxx style, which I think is pretty well-designed.

As ever: Beauty is in the eyes of the beholder. Honestly it wouldn't be my first choice for a gui design model. what I consider to be a calm and clear design might be too boring for others. SVG files are much easier than putting up a whole developer's environment. Maybe I do find the time one far day...

**Comment by mpogue2** [comment]
@Gero5 

re: spin boxes
I think you will like the beat/bar detection that will be in the next release.  It works so well, I was questioning the need for the spin boxes.  It detects the location of the beats, and the beats within a measure, and when you set the loop points, it will snap to the nearest beat (or to the nearest beat 1 of a measure), if snapping is enabled.  I am also pretty picky about loop points, and this feature has eliminated 99% of my loop point fiddling, because it almost always gets it right (that is, the loop back is audibly seamless to me).  

re: Elvira
Yes, this song has 5 seconds of silence at the front.  Adding a "start here" point will not affect the loop points.  It will only effect where playback starts (if you don't force it back to the zero point).  So, with Elvira, I will set it to 4.75s, and eliminate the long wait (during which I am wondering if it's crashed...it never has, but I always wonder during that long long 5 seconds!)

re: Mozart
Ah, I see.  Yes, some of those "edit in the DAW"s might be eliminated, if all you're doing is chopping off the front part of the song (like the situation I have with Elvira).  If you are doing Fade Ins or Normalization or some other editing operations, this feature would not eliminate your DAW work.

re: beauty
Yes, we all have different taste in design.... :-) The other nice thing about SVG's is that you can edit them with a text editor, if all you're doing is changing colors.  I use Inkscape (free), and it works great, especially for changing colors, because I can immediately see the effect.  I've also used the HSV color picker to change the color (hue), while leaving saturation and brightness alone.  That was handy, and it's harder to do that kind of thing with just a text editor.

**Comment by Gero5** [comment]
@mpogue2 

re: beat/bar detection
That sounds pretty cool. You've got me on the hook for the next beta. :-)

re: Normalization
As you mention it: I was thinking if an auto normalization like streaming services have would be a feature for Square Desk. The motivation for that is that I adjust my modern music (radio dance music) to 80 - 90 percent volume otherwise my singing call are too low in volume. On the other hand my singing calls music files are already normalized to 0 dB. But those old productions are recorded differently compared to modern songs where every piece passed several compressors and limiters so the overall loudness impression is much higher. So rather than "auto normalization" it should be a "Adaptive Volume Level Adjust to Human Loudness Reception". I have no idea wether there are ways to calculate that. Even if there was one - adjusting the volume level of a patter music in comparison to the singing call that is played AFTER it is probably a big challenge.

**Comment by mpogue2** [comment]
Re: normalization 
Check out "ReplayGain".  I think it is exactly what you described.   I had an implementation, but it did not work well, so I removed it.  Perhaps I did not implement it correctly?

**Comment by Gero5** [comment]
ReplayGain
Yes, this seems to be the right thing. If I process my files through MP3Gain express and write the volume information to a tag
https://projects.sappharad.com/mp3gain/
would Square Desk be able to adjust the volume due to the tag information?

**Comment by mpogue2** [comment]
@Gero5 All the ReplayGain code has been either commented out or removed entirely from the latest builds.  It's probably a lot easier to bring back the "pay attention to the ID3v2 ReplayGain tag" than it is to bring back the "if there isn't an ReplayGain ID3v2 tag, run the internal copy of the MP3Gain executable to calculate the ReplayGain asynchronously".

It does not take much CPU time to do the extra multiply required to factor in the ReplayGain.  It's mostly UX effort, if all we want to do is pay attention to the ID3v2 tag (with a GUI affordance to turn that on/off).

However, as I recall, it didn't make much difference to perceived listening volume in practice, so that code was removed.  Nobody was using that feature (including me).
