### ISSUE TITLE
Bug: Music Player: Output Volume too low & Boost Intelligibility always ON

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#821]
With the volume set to MAX: Same music played by SquareDesk is about an estimated 30 percent less in volume compared to QuickTime and other music players on Mac. This is a big loss of performance especially when you are working together with other callers.
It also seems to me that the music is loosing a bit of high frequencies when played by SquareDesk. But I am not quite sure about the last point as long as volume output is so different. It is hard to make a fair comparison just by ear.
v 1.0.4 Mac Intel

**Comment by mpogue2** [comment]
I can check it with Audio Hijack or Soundflower...thanks for the report!

**Comment by Gero5** [comment]
even when I try to adjust the music to the same volume level there is some loss in SquareDesk. from the guts feeling I would say less presence. or is it playing everything just mono by default? there is a stereo/mono-button mentioned in the manual but I did not find it?

**Comment by mpogue2** [comment]
- There is a menu option: Music > Force Mono.  Check to see if it's on!

- There is also a "Boost Intelligibility" option in the Global FX tab of Preferences that will gently suppress frequencies in the human vocal range, for improved intelligibility.  

- Below is the result of using Audio Hijack to capture the precise audio from SquareDesk (stereo, mono, stereo with Boost Intelligibility turned off) vs QuickTimePlayer (stereo).  It's definitely down by 6dB.  I'll have to check it to see why that is.  If I recall correctly, that is so we won't have clipping under certain circumstances.  But, with EQ Flat, I would think that the volume should be about the same as QuickTimePlayer.  

- I used to have a compressor in there, but I took it out because nobody was using it (including me).  Note that QuickTimePlayer does not have EQ, and so would not have the same problems with clipping that we might have when for example bass is turned up.  (Might need a multi-band compressor if we want to prevent that...)

- When I have more time, I'll look into frequency response, by using a chirp from Audacity, captured with Audio Hijack...

![image](https://user-images.githubusercontent.com/6316003/232169259-0e9aee64-1d38-44d9-a7ca-da6c9d401c26.png)

**Comment by mpogue2** [comment]
White noise source file (spectrum plot):

![image](https://user-images.githubusercontent.com/6316003/232181501-4720ebe7-44e2-485f-a824-38390dbecfb5.png)

White Noise through SquareDesk (with Global FX supposedly turned off):

![image](https://user-images.githubusercontent.com/6316003/232181398-4bed771b-3307-4825-9334-ba34163d5100.png)

White Noise through QuickTimePlayer (which has no EQ):

![image](https://user-images.githubusercontent.com/6316003/232181470-1130d4e1-8b47-473b-b825-fd448eec6a4d.png)

**Comment by mpogue2** [comment]
So, it looks to me like the Intelligibility Filter is still turned ON, even though it is supposed to be off (that would be a bug).  

However, the QuickTimePlayer doesn't seem to be just passing the audio through either -- it appears to be emphasizing a few frequencies above others (but only by 1dB or so, which would not be audible).

**Comment by mpogue2** [comment]
Same white noise source, with Boost Intelligibility turned ON:

![image](https://user-images.githubusercontent.com/6316003/232181724-ec432fe8-6538-4230-807b-f3fe9771ed77.png)

Looks to me like it's always on, instead of being on only when enabled.

**Comment by mpogue2** [comment]
@Gero5 Looking at the code, looks like I never turn off the Intelligibility Boost.... Nice catch!

**Comment by Gero5** [comment]
Hm. -6 dB technically means it's half the volume (50 %). from a technical standpoint it makes sense to have some headroom for the EQ. from a callers standpoint I would rather have the 100 % output. 
idea: Is it possible to do a quick calculation on the music output before playing. detect the peak output and adjust to that.

frequency issue: When I tried to adjust the QuickTime player I was about minus 35 % in volume. So I guess it sounded more vivid because it was still louder than SquareDesk. It is definitely playing in stereo I tested that too.

**Comment by Gero5** [comment]
re: Looking at the code, looks like I never turn off the Intelligibility Boost.... Nice catch!

I am glad that this was helpful.

**Comment by danlyke** [comment]
Ah! I have been trying to figure out where an occasional crackle on the
Linux build on my Surface Pro 3 was coming from. I thought I'd turned off
all the processing and was ready to chalk it up to something in Qt
processing the floats to output, but now I'm gonna pull and merge and
see...

**Comment by mpogue2** [comment]
@Gero5 regarding peak-detection, that's possible but it will have very strange and counter intuitive effects.  As bass EQ is increased, peak will go up, which if auto-scaled will drop the volume of everything else.  What we would need is a multi-band compressor/limiter, and early on I did not want to add that complexity (and CPU cycles)...

**Comment by mpogue2** [comment]
@danlyke if you turned off all the biquads, you turned off EQ and Boost Intelligibility.  Boost is just the fourth biquad.

**Comment by mpogue2** [comment]
See also #395 .  I would love to be able to leverage a MBCL (multi-band compressor/limiter, e.g. like the free [TDR-Nova](https://www.tokyodawn.net/tdr-nova/)), perhaps on both a global AND a per-song basis, rather than implementing this ourselves.  

That way, we could do "speaker simulation -- make your speakers sound like an MA-220 + Yaks!" at a Global level, while still being able to control EQ for individual songs with a simpler EQ implementation (e.g. perhaps our current one).

The sticky problem I can see is that we want to make these parameter selections persistent, but what if TDR-Nova is no longer available someday?  How would we fall back to another MBCL, if we use it for the per-song EQ?  I think we can probably argue that TDR Nova unavailability making just the GLOBAL EQ parameters invalid is probably OK.

In any case, we still have the problem that ANY EQ is likely to cause clipping.

**Comment by mpogue2** [comment]
OK, the truth is somewhat more complicated here.  There are also two other factors:

1) SquareDesk implements a "constant power" panning law, as do most digital audio workstations.  The pan curves are designed so that the overall volume sounds the same, no matter where the pan control is.  The curves for L and R are based on sin() and cos(), and they look like this:

![image](https://user-images.githubusercontent.com/6316003/232954543-1ad3ae9a-ab12-44d9-b228-88348378145e.png)

When center-panned, a stereo source with this type of Pan Law will have a multiplier of about 0.707X applied to L and R.

2) SquareDesk uses biquad filters for EQ and Intelligibility boost.  Those filters (combined) introduce an additional peak multiplier of about 0.767 for a 1KHz test tone.

So, adding these up for a Stereo signal,  we get:

Output_Amplitude (EQ flat, Center PAN) = 0.707 * 0.767 * Input_Amplitude = 0.54 * Input_Amplitude ~= -5.3dB

That's about the -6dB we're seeing here (slight difference probably due to my eyeballing the measurement in Audacity).

**Options:**
1. We could compensate for these losses (e.g. by always multiplying the output signal by 1.844, which would cost no CPU cycles because we're already multiplying for other reasons), but that would also create clipping artifacts (we have a hard-limiter on here to minimize the artifacts when EQ, in particular, causes overshoot).
2. We could provide a Preference that is a Global Volume multiplier (perhaps with a warning that clipping could result?)
3. We could provide a way to turn off the PAN control entirely, for those people who would never use it.  (I would normally use it for rounds with cues on L and music or R, and for "split-track" MP3's, for example, from Riverboat, but this could also be done externally in the mixer for the few songs that need it, because I use a balanced mixer cable to do the final mix down to mono for the speaker and for the Williams transmitter).
4. Multi-band compressor/Limiter (via VST or build it ourselves).  This is probably the best option, but it's also the most time-consuming.
5. We could turn off the hard limiter entirely, and let the user protect themselves against clipping using the "Audio MIDI Setup.app" volume control for the device.

NOTE: QuickTimePlayer doesn't have this problem, because it does not have either EQ or PAN controls.

**Comment by mpogue2** [comment]
6. We could also switch to Adobe Audition's Left/Right Cut Logarithmic Pan curve.

**Comment by Gero5** [comment]
@mpogue2 
A few thoughts:
- first of all if SquareDesk sets me back at - 6dB at signal level and we do not find a solution I would seriously switch to another music player because of signal to noise ratio and power efficiency in the whole audio chain.
- instead of trading one high sophisticated solution with another or even higher sophisticated solution I like to get back and think wether there might be simpler approaches just to keep it easy.
- for me song-EQ is nice to have, but I would trade it for a boost of +3 dB. I had a few songs that sounded dull  and I gave them an EQ boost in my DSP so I have it permanently fixed at the source.
- same with the stereo pan: I would rather have 3dB than that option (that I personally do not need).
 
So here are a few thoughts for simple/r solutions or maybe a work around before there is something better:
a) is there a possibility to give a EQ and PAN ON/OFF toggle in the preferences and have the music 3 dB louder when EQ or Pan are toggled off?
b) is  it possible to have a toggle on a per song basis. if EQ and PAN are OFF for the song give it the full performance. This could also be an automatic detection. if all parameters are at default bypass the EQ and PAN algorithm. On the other hand you have a strange output set back of - 3dB as soon as you move the controller button. 
c) stereo-pan: I do not have any songs that need that so I am a bit on the dummy side. My thought is: must it allow a continuous mix or would a fixed ratio also be a way of achieving what you need? I.e. would a 'left/right channel only' switch do the job, where the selected channel is played mono on both output channels or any fixed ratio like 30%/70%? 
d) stereo-pan: is it possible to have it at 100 % output when the PAN is at default? and reduce it at a simple linear factor when the controller button is moved? when we are talking about cues on the right / music on the left that is not the 3D stereo impression of an orchestra playing. so why not taking a simpler solution for that. The trade off would be that you have to adjust the output in those cases when you use it. but IMO that is much better than having the need of a 3 dB amplifier boost for all other songs.

**Comment by Gero5** [comment]
@mpogue2 
>re: make your speakers sound like an MA-220 + Yaks

after giving it a second thought: I would like to have my Bose box sound like a Yak but not for the music I would like to have MA-xxx + Yaks sound/performance for the voice. But that is out of squareDesk's reach.

> to make these parameter selections persistent, but what if TDR-Nova is no longer available someday

I think the persistent representation must be some parametric representation of the EQ curve that you want achieve. mainly that describes some peaks. Something like + 1 dB at 1000 Hz, -0.5 dB at 12 kHz aso.  Admittedly there are envelope curves involved and a few more parameters. 
But I am very confident that future EQ systems will be not that different from the basic approach of what to do with the music. So there must be a way to transfer these parameters to another system. (he cloaked his crystal ball after writing this)

**Comment by mpogue2** [comment]
re: persistent representation of EQ
Leveraging VSTs (which is a very powerful feature) means that we would have to go with the parameters exposed by the VSTs, which are generally not just simple frequency/dB key/value pairs.  Some VST's might do just that, most do not.  There is no "standard" EQ interface to EQ-type VSTs, AFAIK.

1. re: Preference to disable EQ and/or PAN
Yes, this is similar to option 2 in my post.

3. re: EQ + PAN == default, then automatically bypass entirely
Yes, this is possible.  It has the disadvantage that the EQ and PAN curves are no longer continuous, that is, there will be a sudden drop, as soon as either one is no longer at the default position.

4. re: a fixed pan ratio
No, that doesn't work for either cued rounds (Voice on L, Music on R) or split track songs (e.g. Music on L, Harmony on R), where the relative volumes need to be adjusted continuously, rather than discretely.  The use of a "constant power" curve is what allows this use case to work correctly, with the disadvantage of the -5.3dB.

5. re: "simple linear factor".  No.  This creates a "hole" in the middle of the range, as explained [here](https://www.cs.cmu.edu/~music/icm-online/readings/panlaws/).  What might work better, though, is the "left/right cut logarithmic" approach that is used by Adobe Audition, plus the addition of a global preference, selecting either the current "constant power" pan law, or this new "logarithmic" pan law.  Unfortunately, although I understand how to implement the "cut only" part of what Adobe Audition did, I do not know how to implement the logarithmic part.  If somebody has Adobe Audition, and we can measure that, that would help, OR if you can find documentation on this approach, that would help (I could not find docs on this).

**Comment by Gero5** [comment]
@mpogue2 Pan/Stereo Balance 
I understand your use case as such that the user wants a mono mix of two channels.
- channel A: with the voice cues/calls 
- channel B: with music. 
So to keep it simple IMO two separate controllers like in the Windows system settings should do the job.

![Bildschirmfoto 2023-04-24 um 10 13 54](https://user-images.githubusercontent.com/128936259/233940638-50144dd2-7a21-47f1-a77e-c808c547a84b.jpg)

> NOTE: QuickTimePlayer doesn't have this problem, because it does not have either EQ or PAN controls.

In a way QuickTime has a pan/balance option. MacOs has a balance controller in the system preferences that can be used for that. Is SquareDesk able to make use of that instead of implementing it's own pan solution? 

> re: Adobe Audition, and we can measure that

Maybe you can measure the output curve of the MacOs's system preferences audio balance controller?

![Bildschirmfoto 2023-04-24 um 10 41 15](https://user-images.githubusercontent.com/128936259/233945554-437bbe8a-9b07-4d8d-acff-8a8a402ed47a.jpg)

**Comment by mpogue2** [comment]
Additional info: https://www.hackaudio.com/digital-signal-processing/stereo-audio/sine-law-panning/

**Comment by mpogue2** [comment]
Additional info: https://www.admiralbumblebee.com/music/2019/12/08/Daw-V-Daw-Pan-Curves.html

**Comment by mpogue2** [comment]
Additional info: https://www.harmonycentral.com/articles/recording/the-truth-about-panning-laws-r501/

Another possibility: We could provide a Pan Compensation preference (e.g. 0, +3, +6dB).  I would leave it at 0 (which, in combination with the sine pan law gives a 3dB drop in each channel), but those who are willing to risk clipping can set it to compensate for the drop at the center pan position.  This would be fairly easy to implement, too.

**Comment by mpogue2** [comment]
Commit: 32f346ba66d2bf6c8e2660bee4cfa002b4a08c29

Boost Intelligibility was stuck ON (since the rewrite to eliminate libbass), but now it correctly pays attention to the ON/OFF setting in the Global FX preferences tab.

Tested with white noise, analyzed in Audacity:
BI OFF:
![whiteNoise_BI_OFF](https://github.com/mpogue2/SquareDesk/assets/6316003/98eec8d2-7fce-453c-9f6a-545157e5c0eb)

BI ON:
![whiteNoise_BI_ON](https://github.com/mpogue2/SquareDesk/assets/6316003/f151bc13-086b-4035-88ad-0090cd274894)

**Comment by mpogue2** [comment]
Commit: d1cfd32f0b4f6bbf0e59f5fd68b6c80c63264f7e

The Constant Power Pan control (sine-function-based) introduces a multiplier of 0.707 in both channels when the Pan control is centered.  And, EQ introduces a multiplier of about 0.767 when all the EQ controls are at center position.  

To compensate for this, a preference in the Global FX tab now allows for boosting (or reducing) the volume for all songs by -10 to +10dB.  For those who want to compensate, and are willing to take the risk of clipping when non-default PAN or EQ settings are used, this dial would be set to about 5.5dB (results in a factor of 1.0/(0.707 * 0.767)).

Since many square dance tunes are normalized to 0dB, setting the dial to 5.5dB is likely to cause audible clipping distortion when the Pan control is centered, and any of the EQ controls is set to a value higher than 0dB (centered).
But, for people who don't use SquareDesk's Pan and EQ controls (perhaps they use an external mixer for Pan and EQ, or perhaps they do not use Pan or EQ controls), 5.5dB is a good setting for this dial.

**Comment by mpogue2** [comment]
OK, I've drawn up a quick diagram of how this works now.  This comment has added the GREEN boxes labeled "Gain" to the Audio Pipeline.

![Diagram_MONO_STEREO](https://github.com/mpogue2/SquareDesk/assets/6316003/f212945e-502b-43a5-bffc-5686b8f32363)

**Comment by mpogue2** [comment]
The choice of "pan law" has been hotly debated for quite a long time. :-)
See also this reference: https://www.soundonsound.com/sound-advice/q-what-pan-law-setting-should-use

I think there's also an argument that we're most often in what this article calls the "constant level when summed to mono" use case (because most callers output to mono -- I certainly do), which suggests a -6dB center pan point (!).

I thought that you were in the "I never really use the Mix control -- it's always in the center" use case, is that still correct?  If so, then would the compensation knob (added as per [this](https://github.com/mpogue2/SquareDesk/commit/d1cfd32f0b4f6bbf0e59f5fd68b6c80c63264f7e) commit) handle both the Pan Law and the EQ compensation for you?

**Comment by mpogue2** [comment]
@Gero5 At least in the short term, IIRC you don't really use the Mix control, so you're probably OK for now (when you get the makeup gain control version of SquareDesk).

Ultimately, a lot of the DAW vendors put in a preference for the Pan Law used by the "whatever-we-call-it" control, and maybe that's the best approach here, too.  I'll open a new Feature Request for that.

**Comment by Gero5** [comment]
> At least in the short term, IIRC you don't really use the Mix control

Yes, you  caught me on this. ;-) As I user I am totally satisfied with the output boost to 0 dB and I would not have any clipping problems when the pan/bal controller is on extreme positions because I never move it there. Admittedly the rest is a rather nerdy discussion between you an me and I will not bother you a further with it. However, I learned a lot about pain rules on the way. :-)

>  put in a preference for the Pan Law used by the "whatever-we-call-it" control,

Please don't. Except you an me none of the users understands the difference anyway. I think there is no need for that.
