### ISSUE TITLE
Feature: Sequence management: Add comments after the fact

### ISSUE THREAD

**Issue by danlyke** [mpogue2/SquareDesk#826]

**Comment by mpogue2** [comment]
I think this might look something like this (since I really don't want to implement the full Edit Call in Middle of Sequence functionality right now, due to its complexity):

- **Right click > Add comment**
   Brings up a dialog with one label (current call) and one text field (in the suffix position).  
   Can add suffix comment only right now.  CANCEL and SAVE buttons to exit.
- **Right click > Delete comments**
   This would delete all comments on that line -- prefix and suffix.

**Comment by mpogue2** [comment]
Implemented by: 3661fcade3b7a1afb13fe87158c74160e6185c08 .

NOTE: The sequence must be UNLOCKED to be able to edit comments.

NOTE: Only SUFFIX-type comments are supported to be added this way right now.
For example, the line:
`Swing Thru`
could have a comment added at the end like this:
`Swing Thru ( Boys in the center )`

PREFIX-type comments like `( Corner box ) Swing Thru` could be a future enhancement to this new dialog, but they are not supported right now.

**Comment by mpogue2** [comment]
This seems to work and is stable, so closing.
