### ISSUE TITLE
Inconsistencies between next and previous song

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#841]
There are several places where the next or previous visible row is searched for.  It would be nice to refactor them into one common one.

However, on_actionNext_Playlist_Item_triggered and on_actionPrevious_Playlist_Item_triggered have differences not just in whether they search forwards or backwards.

on_actionPrevious_Playlist_Item_triggered moves “up” in the list on if at the beginning of the song, otherwise it goes to the beginning of the song.
(Is this difference in behaviour intentional?)

on_actionPrevious_Playlist_Item_triggered loads the pitch and tempo settings from the new line but on_actionNext_Playlist_Item_triggered does not.

**Comment by mpogue2** [comment]
1. The "moves “up” in the list on if at the beginning of the song, otherwise it goes to the beginning of the song" behavior is intentional.  This is because most music players work this way.  If you're in the middle of a song, and you hit |<<, it goes to the start of the song.  If you hit |<< again, you go to the previous song.

2. I just tested J and K keys.  The K key does not set pitch and tempo to those of the new one, but instead the old pitch/tempo are associated with the new song (and are saved that way!).  J key has the same problem. BAD MIKEY! :-)

**Comment by mpogue2** [comment]
OK, fixed by 945c4394154d34f9e293d5905206ea1a2877bca6 .

Let me tell you what happened here!  This was a really good catch from code inspection, by the way!

The J and K keys did NOT set tempo and pitch correctly.  Worse, the bad values were now saved in the database.  This was broken (yes, by me!) when I switched to the new audio infrastructure, which got rid of libbass (a NON-open-source library, that was painful to use because we had no visibility into what it was doing inside).  We now use the Qt Multimedia infrastructure, which is cross-platform and Open Source.

But, as a consequence of the new architecture, loading a song now happens in TWO phases:
- start the load going
- when the load finishes, use miniBPM (also open source, unlike libbassfx) to determine tempo, and finally, use the target pitch and tempo to set the sliders, which in turn sets up SoundTouch (also open source) for playback.  Phew!

In the old architecture, there was only a single phase, and so setting the tempo and pitch at initial load time worked fine.  With the new two-phase architecture, the SECOND phase is what does all that work.  I had commented out PART of the J and K code, in anticipation of fixing it to look like the Double Click On A Song code, but it looks like I never went back and fixed that.  And, since I don't use the K J and K keys, this never got fixed or even checked for correctness by me.

I started to fix this by adding code to on_actionPrevious_Playlist_Item_triggered and on_actionNext_Playlist_Item_triggered.  This actually worked fine.  But then I realized that because Double Click worked fine, I should just have those functions figure out which row is the next/previous visible row, and then call the Double Click code....Voila! everything now works, and the code is a lot simpler.

So, nice catch, @sharmanr!  Code is now much simpler, easier to maintain, and it actually works as-designed now.  It turns out that the new code also avoids an extra call to on_pitchSlider_valueChanged, so it goes faster now, too!
