### ISSUE TITLE
Bug: Moving song down or up in playlist doesn't stop at max list number (going down) or 1 (going up)

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#844]
Suppose the playlist has 6 items in it.   When a song is selected and "Move DOWN in playlist" repeated the playlist number doesn't stop at 6 but can grow arbitrarily higher.

Similarly, selecting a song then repeating "Move UP in playlist" can cause the number shown in the playlist to be negative.

<img width="433" alt="ss" src="https://github.com/mpogue2/SquareDesk/assets/76225465/62ae08b5-bcca-4ecb-849f-24ef854c161f">

**Comment by mpogue2** [comment]
Very nice catch!

Fixed by 6ceaea4a8a597ebe26da85b2d80da0bbf2ab87e6.

Using the CMD-SHIFT-UP key, it was possible to make the item number in a playlist less than 1.  Similarly, using the CMD-SHIFT-DOWN key, it was possible to make the item number in a playlist greater than the number of items on the playlist.  But wait, there's more!  It was also possible to use those two keys on NON-playlist items, and hilarity ensued.
