### ISSUE TITLE
Bug: Coming out of Preferences dialog, songTable is re-sorted

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#89]
It should leave it the way it was when I entered the Prefs dialog.

**Comment by mpogue2** [comment]
A related issue:  When restarting the program, perhaps the sort order should be persistent?

**Comment by danlyke** [comment]
Happens when we re-read the folders. Two possible answers:

1. Detect that nothing changed in the prefs dialog. This has the big con of needing to check for changes in music names, music types, and the folder.
2. Sort pathStack. I kinda like this notion...

And, yes, I kinda think sort order should be persistent. Maybe even scroll position.

**Comment by mpogue2** [comment]
I agree that sort order should be persistent, and scroll position too...nice idea!

**Comment by mpogue2** [comment]
OK, if you hit CANCEL, the songTable is NOT repopulated, which does preserve everything.
If you don't change anything, and hit OK, then the sort order and scroll position are lost.  This is because if the Music Directory or Music Names or Music Types or Type Colors changed, then we **do** need to repopulate the table.  Otherwise not.  
Maybe this is a simpler problem?  That's only 10 things to check to see if they changed.

**Comment by mpogue2** [comment]
OK, everything (sort order, selection) is persistent now, if you don't change anything that requires updating the songTable, and you click OK.  If you click CANCEL, it will also not reload the songTable.
Commit: 5e35c9b0bada66027bc34dd0c80cdbdf24da81dd .
