### ISSUE TITLE
Feature: better default intro/outro for singers (was: default time for tag part in singing calls is too long)

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#897]
I do not know wether something has changed here. I just have the feeling that it was better before...
Default time for the TAG part coloring of a singing call is at ca. 20 seconds before the end of the song. 10-12 seconds before the end would be better. I think that is was closer to that before but I am not quite sure.

here the singing call total time is 3:44. the yellow section starts at 3:24. In/Out was not set manually.
![image](https://github.com/mpogue2/SquareDesk/assets/128936259/b03b106c-79e0-4c4d-a22f-a559f2be03f7)

examples: SIR 0368 dixieland delight, RBS 1250 Coca Cola Cowboy

**Comment by danlyke** [comment]
I probably set this initially, though I have no memory of it, and I think
the right way to do this is assume 126BPM, give, say, two measures for
intro (7.6 seconds), assume that 7 64 beat phrases comes out to 3:33.3, so
start the tag at 3:41... (trying to figure out if my numbers are right,
'cause I've generally assumed 3:42 for singing calls, and that now seems
short).Message ID: ***@***.***>

>

**Comment by mpogue2** [comment]
@danlyke  I wrote this code about 6 years ago.  It's located at L68 in MySlider.cpp, and here's the basic idea:

- The start of the song is considered to be at T=0.0, and the end at T=file.length
- We calculate the length of a 32-beat phrase, given the current estimated BPM (which is almost always correct).
- The initial INTRO is set to 5% from the start of the song.  Note: it does not current hunt for the actual start of the song, because that could be a partial phrase -- there's no way to know what the song intro does anyway, so 5% is just an approximation.
- Note that we also no longer do silence detection (originally part of #231).
- It then moves forward by as many 32-beat-phrase lengths as will fit into the remaining time in the song.  That is most often 7.  Note that we don't assume 126BPM -- we use the actual BPM of the song (as best as it is known).
- If it is able to fit more than 7, it moves back one (see #330).

I tested this on a bunch of files, and it worked pretty well as an initial approximation.  

Two comments:
1. I would really like the music producers to set an ID3 tag with the intro and outro.  Same for patter -- THEY should tell us where the loop points are, so we don't all have to figure out the sample-accurate loop/intro/outro points ourselves. Sheesh!
2. In the mean time, see #806.  I've tested this code manually (see the issue writeup), and it seems to work pretty darn well.  This is the way that I'd really like to proceed, for both patter loop points and singer intro/outro points, until we can get the music producers to do that for us.  Yeah, I know that setting it manually doesn't take more than a few seconds, but I think that with this new library we can do a far better job than we are doing now (especially for Patter, where I really really want the default to be as close to sample accurate as possible -- singers are far less critical, since it's just coloring of the playback timeline that is affected).

**Comment by mpogue2** [comment]
Now that the code for #806 is in (and working), we might want to change the default Intro/Outro points for Singers to something like:

- Intro: Beat 1 of the 5th full measure from the beginning of the song
- Outro: 7 * 64 beats after that beat (also Beat 1 of the first Tag measure)

This is a guess, because the length of the Intro section is not a fixed length. But, this is probably closer than what we do today.  

Any thoughts?

**Comment by danlyke** [comment]
I'm good with a reasonable and better guess than what we've got. Especially
if you think you're detecting measure starts reliably.

**Comment by mpogue2** [comment]
I forgot... This would add ~2 sec to load time.  Maybe needs a button to initiate it...

**Comment by danlyke** [comment]
Agree on the button..or at least limit it to only the first load of the
song. 2 seconds is an eternity when the floor is waiting....

**Comment by mpogue2** [comment]
Measure detection seems to be pretty solid.  But, it's current asynchronously finished (to save user perceived time), so it's actually not available until a few seconds after load.  This is normally OK, because a user doesn't press the [ or ] buttons for several seconds after load.  If they DO happen to do this, then we wait for an extra second or two.

Now, it's probably not normal to be playing a singing call for the very first time at a dance.  So, we might take those extra 2 seconds on the very first playback in SquareDesk, and that would set the intro/outro to their (better, beginning of a measure) default values, and would cache the result in the DB, then we wouldn't have to run it again for this song (until the song changed out from under us, the cache invalidation question).  So, 2 second penalty on the very first load (or the first load after the files modification date was changed), and essentially zero second penalty on subsequent loads.

Right now, there's no cache, because caching is always harder than it seems.  So, the beat/bar detection is always done at load time right now.

**Comment by mpogue2** [comment]
It's one keypress ( SHIFT-[ ) to set intro and outro for a singing call, now that #1015 has been implemented.
This uses the new beat/bar detection algorithm that appears to be quite robust so far.

#1035 will track the upfront (in advance) calculation of beat/bar detection (using QtConcurrent for parallelism).

So, closing this one in favor of #1035.
