### ISSUE TITLE
Playlist Save As is disabled after adding to empty playlist

### ISSUE THREAD

**Issue by sharmanr** [mpogue2/SquareDesk#928]
Invoke SquareDesk with no playlist (or Clear if there is one).
Add a song or to the playlist.  You should be able to save it but the Save As button menu item is greyed out.
(If you Quit you **do** get the option to save, though when you re-enter SquareDesk it doesn't default to using that newly saved playlist.)

**Comment by sharmanr** [comment]
Actually, I find it doesn't seem to remember the last playlist when one was used on the last session.  So I think there are 2 problems not 1.

**Comment by mpogue2** [comment]
@sharmanr I've been mucking around a lot with playlists today, so I may have broken something along the way....
Exactly which commit did you try?  I'll try to duplicate here, and look at it...

BTW, can you compile DARKMODE?  I'd love to get some feedback from you on where I am with the DarkMode prototype tab (turning on DARKMODE will mess up the Music tab right now, so you'll have to turn it off again when done testing...)

**Comment by sharmanr** [comment]
It was pulled about 90 minutes ago.   I can’t tell from the command line nor github desktop, but looking at gitkraken I think it was 4d7c72fabe999ecd73bf59cb70f4ad45a6b3751a [4e7d72].

**Comment by mpogue2** [comment]
Commit: 10db714e96a3d83f6e18b422d3f045b2e1192667

Sorry!  I had commented out some lines having to do with initial playlist load in NON-DARKMODE which should not have been commented out.  

While I was fixing that, I provided a SMALL amount of forward compatibility with DARKMODE.  So, the latest top-of-tree should be able to see and use playlists and recent playlists set by the 1.0.5 version.  However, the reverse is not true.  Once you start using hierarchical playlists, you gotta stick to the top-of-tree version and later.  If you do go backwards, just clear them out of the Recent Playlists list -- they aren't harmful to anything, they just won't load, because 1.0.5 was unaware of how to do hierarchical playlists.

**Comment by sharmanr** [comment]
Thanks, it builds now.   I haven't looked at hierarchical playlists yet -- I've been out of the loop for a while!

**Comment by mpogue2** [comment]
They are brand new!  I do a playlist for every night I call.  So, I have now hundreds of them, and I can't stick them in a simple list.  The DARKMODE version has a TreeWidget for presenting playlists for selection, so it's natural to group playlists like this:

- Jokers
    - 2020
        - playlist 1
        - playlist 2
    - 2021
        - playlist 1
        - playlist 2
- ECR
    - 2020
etc.

Playlists can have the same names now, if they are in different folders in the hierarchy.
darkMode playlist implementation also allows us to have the same song more than once in a playlist.
And, as you might see from some of the pics in #921, we can view up to 3 playlists (or track filters) at the same time now.

**Comment by mpogue2** [comment]
DarkMode version also provides:
- waveform display
- modern look for controls
- ability to view and fix broken playlists much more easily
- beat and measure detection (one-click setting of loop start/end points, no more fiddling with microseconds)

**Comment by mpogue2** [comment]
I think this one is fixed now, so closing.
