### ISSUE TITLE
Bug: Switching to Music tab in Dark Mode sets focus to the hidden titleSearch field

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#941]
play a singing call
press the loop button
the player loops

I expected that another klick on the loop-button will end the loop. It did not.
press "L" does not work - but has some strange effects on the music list

press "L" several times: the music list is empty
this happened more than once, but I am not able to reproduce this(?)
after minimizing the window (or whatever it was), everything on the list was back and loop was reacting as expected on "L" and the button.

**Comment by mpogue2** [comment]
@Gero5 Where was the "focus" when you did this?  If the focus is in the Search field, for example, the "L"s will go there (and will narrow down the search until the song list shows zero entries).  

If the focus was in the search field, how did it get there, in your normal way of loading a singing call?  This could be a focus error of some sort...

**Comment by Gero5** [comment]
> Search field, for example, the "L"s will go there

I thought about that myself. but firstly I have a lot songs containing a "L" even a search for "LL" has many results.

> until the song list shows zero entries
 
for "LLL" maybe. I cannot say that it is totally impossible because of the new gui.

**loop button:**
Is it intentionally that the loop button is a toggle in the first place and then turns into a "test loop" button? does it make sense for singing calls? maybe it is better to grey that out?
on the other hand if you want to use a singing call for patter calling the auto detected loop positions are perfectly placed.

**Comment by Gero5** [comment]
ah here we go able to reproduce the use case:

(autostart play is turned ON) - do not know wether that has any influence

1. load a singing call
2. set the mouse curser on the loop button.
3. klick on loop button and leave the mouse cursor on the loop button(!)
4. hit the "L"-key several times

--> the loop feature does not react to the shortcut (it does, when CMD-L is used)
--> the music title list is empty, although search field is empty

at this stage go on with:
1. type something in the search field
2. clear search with "x"

--> music titles are displayed again

clear suspect: although the user does not click in the search field somehow the "hitting a key" turns into a search that is not displayed in the search field.

**Comment by Gero5** [comment]
loop Button:
I think a clear ui would be

- one switch/toggle for loop ON/OFF 
- and a separate "test"-button, greyed out when loop is inactive

**Comment by mpogue2** [comment]
The L key is what we use to turn looping on/off.  The "Loop" button is really "Test Loop" right now.
Changing this to a Feature Enhancement, since a button equivalent for the L key seems like a reasonable thing to do.

**Comment by mpogue2** [comment]
OK, I've been able to duplicate the behavior, but it requires a very specific state:  the focus has to be in the search box.
Then the "L" key goes to search, and it narrows down the entries in the songTable.

But, there's another related problem with focus:  the ENTER key and ARROW keys do not work if I filter the songs using the Tracks portion of the TreeView.  This is because ENTER/ARROWS are valid when focus is in the songTable or the search box, but when we click on the TreeView to filter the songTable, the focus should go to the songTable, and it does not.

I think I can fix both of those.

**Comment by Gero5** [comment]
> the focus has to be in the search box.
as soon as I klick the button the focus should not be on search any more even if it was before.
in my case pls note that I did not click on search and the search box does not show the "lll". the focus was set by the system.

**Comment by mpogue2** [comment]
Commit: 387a7f92f8a65e24f5e20aafbae3577044b93a77

Fixes the problem with ENTER/ARROW keys not working after either: 
- right-clicking in the TreeWidget and selecting "Show in Palette Slot #N"
- double-clicking in the TreeWidget to load a Palette Slot.

**Comment by mpogue2** [comment]
Hmmm....I have been unable to duplicate the problem you described as:

```
- load a singing call
- set the mouse curser on the loop button.
- klick on loop button and leave the mouse cursor on the loop button(!)
- hit the "L"-key several times
```

In my testing (with the latest top-of-tree version, **including the focus changes I just made**), no matter how I load the singing call, or where I put the mouse cursor after clicking the loop button, the L key works to toggle the Loop [ ]'s on and off every time.  

I am thinking that this is because the focus has now been explicitly set to the songTable (as opposed to the dark search box or the hidden regular search box).  I had suspected that the problem was related to focus, and I think the latest changes I just made have fixed both problems.

**Comment by Gero5** [comment]
> I have been unable to duplicate the problem

- quit SquareDesk and restart it.
- double klick on a singing call in the title list, so a the music is loaded and  it plays because auto play is on
- cuesheet is displayed, click on the music tab
then do this
```
- set the mouse curser on the loop button.
- klick on loop button _twice_ and leave the mouse cursor on the loop button(!)
- hit the "L"-key _three_ times
```
same results every time I do that here.
