### ISSUE TITLE
Bug: Clicking in the seekbarCuesheet doesn't jump there (Dark Mode bug only)

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#943]
the cursor will jump forward one mark, after the fifth it jumps to the start

**Comment by mpogue2** [comment]
@Gero5 I have not been able to reproduce this one here on M1 MacBook Air.  
Am I doing the right thing to reproduce the bug?

![2023-11-22 17 26 32](https://github.com/mpogue2/SquareDesk/assets/6316003/89ec6fa0-be8d-4917-a9af-f879447fc3be)

**Comment by mpogue2** [comment]
OK, the root cause of this one was the switch to the Fusion style.
`a.setStyle(QStyleFactory::create("Fusion")); `

Everything works as before in Light Mode, because it does NOT change the style to Fusion.  I have literally no idea why the Fusion style alters the way clicking in a slider works.  I was unable to decipher the Qt source code -- it looks like it doesn't touch anything to do with QSlider behavior.

So, this commit tells the seekBarCuesheet when it's Fusion mode, and when it is, it manually implements click-to-jump.
Yuck, but it works.

15be93e2531e10956b3ae1afd3df78fb902c6762

What doesn't work is click-and-drag, because that will require a bunch more work.  I wanted to get click-to-jump working as soon as possible for Dark Mode.
