### ISSUE TITLE
Bug: playlist entries are marked as "not found" although the files exist

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#946]
See screenshot. I guess the files marked red in the playlist mean "not found". the missing titles are in the music list.
Is it caused by the artist's name in the file name?

![Bildschirmfoto 2023-11-22 um 10 04 54](https://github.com/mpogue2/SquareDesk/assets/128936259/d6b79e9c-3332-4ceb-a61f-56ace14ae663)

**Comment by mpogue2** [comment]
@Gero5 Yes, red strikethrough are items in the playlist that were not found when we tried to find that file on disk.  It is the updated error mechanism for playlists.

My guess is that this is not due to the artist's name per se, but rather that for these files there is no label field, yet there IS a "-", which normally separates label and title (e.g. "ESP 0601 - Gonna Have A Party").

We do quite a bit of "fuzzy matching", so that we can decode filenames like "Gonna Have A Party-ESP0601" (label after title, and lack of spaces).  But, if the filename is "Electric Daisy Violin - Vanessa Sterling.mp3" then we can't figure it out.

I wouldn't think that would matter here, but maybe it does for some reason....

Questions for you, to try to narrow this down:
- Is the "Darmstompers" playlist one that you had from a while ago?  (It's dated 2023-04-12, I think).  In other words, it's NOT a brand new playlist that you just created, right?
- Is "1 -800" really a file in that playlist?  "900" too?
- Does this playlist open OK in V1.0.5?  Or does it give you errors because it can't find the files?
- Maybe you could send me the playlist, and also just tell me the exact names of the files referred to, *full path names, as they are on your disk right now*, and I can probably reproduce this here pretty quickly....
- Also try RIGHT-CLICKing on the red strikethrough items, and see what they are trying to reference. 

Thanks!

**Comment by mpogue2** [comment]
@Gero5 If you have a chance to take a look at the above questions, I can dig into this one....need more info here...thanks!

**Comment by Gero5** [comment]
the pure filenames are 'Electric Daisy Violin- Vanessa Sterling.mp3' and 'Stampede - Vanessa Sterling.mp3'.
I think I never changed the name. I cannot tell from the modification date, because iCloud is deleting my music files after a while and I have to force it for a new load and all files have the timestamp from that reload.

playlist entries
>"/patter/Electric Daisy Violin.mp3",0,128
>"/patter/Stampede.mp3",0,131


> Is the "Darmstompers" playlist one that you had from a while ago? (It's dated 2023-04-12, I think). 
>In other words, it's NOT a brand new playlist that you just created, right?

yes 

> Is "1 -800" really a file in that playlist? "900" too?

yes filename '1-800.mp3' and '900.mp3'.
that is a patter record SIR 504. Named by telephone numbers. it was renamed to 1:800 / 911 somewhere between 1995 and now. 

> Does this playlist open OK in V1.0.5? Or does it give you errors because it can't find the files?

it opens buts. the v. sterling titles are vanished then.
 
I think it is likely that I renamed the files and do not remember.

**Comment by Gero5** [comment]
I think it is likely that I renamed the files and do not remember.  I will reopen that if it happens again.
