### ISSUE TITLE
Bug: Export Play History does not filter properly, possibly when yy.MM.dd HH:mm format is used

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#947]
this was my search - I was expecting results matching local time

![Bildschirmfoto 2023-11-22 um 10 32 00](https://github.com/mpogue2/SquareDesk/assets/128936259/1dff9718-9adf-4579-88ca-bbc808fddf93)

in the database there are several song entries matching the search (list of all entries generated with v 1.0.5)

![Bildschirmfoto 2023-11-22 um 10 36 45](https://github.com/mpogue2/SquareDesk/assets/128936259/7c19fb2b-e31c-466e-a37e-0fb9b757fa2e)

However the resulting list is empty. 
local time format / 24 hrs format?

**Comment by mpogue2** [comment]
@Gero5 Hmmm...those datetimes not 1 day apart, so they can't be the default times.

1) So, I'm guessing that you changed the start and end times manually? If so, could you try entering the date times as "yyyy-mm-dd HH:mm" and see if it works then?  If it works, then I think we might be hitting an I18N (internationalization) problem here with the "yy.MM.dd HH:mm" format that you are using.

2) On the other hand, if that was the format that came up for you when the dialog opened up (the default start and end times), then we might have a different problem (and I'll probably have to make you a special debug release in order to help track it down).

3) Does version 1.0.5 have the same problem?  My guess is that it does.  I don't think I changed anything in this area for V1.0.6, so this might be a long-standing bug, instead of one that I just introduced.

**Comment by Gero5** [comment]
yy-mm-dd is how it is displayed by SquareDesk when the dialog is shown. i did not cut the year by two digits

I was able to get the data of a specific clubnight in v 1.0.5. but I can test that later.

**Comment by Gero5** [comment]
I think the user (me) was too clever Wich means was the problem in this case.
