### ISSUE TITLE
Feature: Allow the volume control to go above 100%

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#948]
I have calls recorded at different levels

new songs look like this (0 dB is reached throughout the song)
![Bildschirmfoto 2023-11-22 um 12 17 58](https://github.com/mpogue2/SquareDesk/assets/128936259/71e20657-21d5-401e-a946-07509c581163)

other mostly older recordings like that
![Bildschirmfoto 2023-11-22 um 12 17 23](https://github.com/mpogue2/SquareDesk/assets/128936259/42f773e2-1e25-41d5-b07d-7800c2dc2cf4)

I was wondering if a (up to) plus 3dB or so  for the song volume controller. At the moment I am pressing the volume of the new songs down, but I would rather have it the other way. I know that there is a risk of clipping and I am personally able to deal with that (maybe not every hapless caller).

BTW: the volume value is missing in the database report **Song Play History**. 
a) as a nerdy work around: would it be possible to put a volume value of e.g. 130 % in the database for a song just by sql editing?  Would the player play a higher gain then?
b) Allow adjusting volume over 100 %. May with a secure mechanism so that by default if I push the volume up it will stay at 100% and I have click something (e. g. pop up message) if I really want to go over.
related to #922

**Comment by mpogue2** [comment]
I am leaning toward fixing this with Replay Gain, instead of a new feature.  That way, you can still adjust this on a song-by-song basis, using an external program.  And there are some apps that will adjust ALL of the songs in your catalog at one time.  You could even set a value that provides more/less gain than ReplayGain would provide, if you want to.

Now, should the waveform reflect the ReplayGain?  Since this is not a dynamic change of volume (which would introduce performance problems), I am inclined to say "YES, the waveform should reflect the gain AFTER ReplayGain is applied.".

**Comment by Gero5** [comment]
clipping indicator: how about a red light (or something similar) above the vu meter? that seems to be the  logical place for me.
I would leave the waveform showing the song as found in the mp3 file. the new version is already slow on loading a song on my system.

**Comment by mpogue2** [comment]
A red clipping light might be a nice feature, in addition to implementing the ReplayGain tag.

**Comment by mpogue2** [comment]
See #954.

**Comment by mpogue2** [comment]
Superseded by #954, so closing this one.
