### ISSUE TITLE
Bug: Intro and tag sections don't show up on first load of a singing call

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#949]
on the player
![Bildschirmfoto 2023-11-22 um 14 43 21](https://github.com/mpogue2/SquareDesk/assets/128936259/0ae04174-08ff-430b-bd1c-15762c8abb80)

on the cue sheet tab:
![Bildschirmfoto 2023-11-22 um 14 43 30](https://github.com/mpogue2/SquareDesk/assets/128936259/c1951b4d-8a8a-42eb-94e1-dae3d02043ed)

**Comment by Gero5** [comment]
it is not always reproducible. maybe on first load of the song?

**Comment by mpogue2** [comment]
Reproduced that bug here.  Yes, it looks like the first time it plots the waveform it's incorrect, but subsequent waveform plots are correct.

**Comment by mpogue2** [comment]
OK, the problem was far more extensive than I originally though.  There were a couple of things that were not getting set on that very first load, when default intro and outro times are set.  The seekBars were correctly colored, but the intro/outro date times (the editable fields) weren't getting set either.  AND, the set intro/outro buttons ('[' and ']' in darkMode) were not working correctly either.  

All of the above problems were ONLY on the very first load of a new song.  Subsequent loads were fine.

This bug has been there since way before this release (I checked and the date time fields part of the bug was present in 0.9.5).

Anyway, I think I fixed all of these related problems, and I reduced the darkMode load time for singing calls by making many fewer calls to updateBgPixmap() (reduced from 6 to 1).

Commit: a67c956979cd24f034b73ed6754ec0e7762771ff
