### ISSUE TITLE
load playlist from menu only loads to palette #1

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#953]
it is a bit strange that from the menu the playlist only goes to paltte no. 1

I think a way for a better implementation could be either
a) to ask for palette no
b) to put three load playlist entries in the menu
c) to load it to the next free palette, i. e. when palette # 1is already loaded then put the playlist palette # 2 aso. if all three are full show a popup dialog and ask for the paltte no. to override

I think c) is the most clever one.

**Comment by mpogue2** [comment]
It works almost like your c) description.

Right-clicking in the Tree View (underneath the Search box) brings up a context menu to load to Palette slots 1, 2, or 3.
But, DOUBLE-clicking in the Tree View (underneath the Search box) will load to the next free palette.  If they are all full, it will load to the third palette slot.

If you are seeing only a menu that goes to Palette slot 1, could you take a screenshot for me?  Thanks!

**Comment by Gero5** [comment]
> Right-clicking in the Tree View 

I discovered that and it works well. 

menu means the title/overhead menu (or what would you call that for further reference?)
menu: Playlist/Load Playlist

<img width="583" alt="Bildschirmfoto 2023-11-24 um 10 05 17" src="https://github.com/mpogue2/SquareDesk/assets/128936259/133e838c-36bd-46af-99a7-cafeadd33953">

**Comment by mpogue2** [comment]
Ah, got it!  That's actually the old (now Light Mode) Load Playlist, back when there was only 1 playlist that could be loaded at a time.  With the new UX, you're right we should be able to expand that to 3.

Save Playlist actually should be removed, because playlists are now automatically saved when they are changed.

Not sure what to do with Print, Add, Move, and Remove.  All of those could in theory have 3 variants, which seems like a lot.

I'm wondering if I should just move all of those functions down to the right-click (AKA context) menu for each slot.  It's a lot cleaner.

But this is a good catch.  Either it should explicitly say Slot 1, or all the functions should be expanded to 3, or all should probably move down to the context menus.

Let me think more about that.

**Comment by mpogue2** [comment]
And, the way I normally refer to the top-level menu items is with this format:  "Playlist > Load Playlist...".

**Comment by mpogue2** [comment]
I'm gonna close this one, given the approach taken by #956 and #957 (move these functions to the slot context menus).
