### ISSUE TITLE
Feature: palette context menu: add "Load playlist", "Save Playlist As...", and "Print Playlist..."

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#956]
would be a good feature.
At the moment there is no load or save and no context menu at all for empty palettes.

the list could be (only shown where applicabel)
- load 
- save
- Text edit playlist
- reload
- remove

**Comment by mpogue2** [comment]
Commit: 757f51824aea21f42eef3db24975d0c7a1d46972 implements

- Right click > Load Playlist... (available for all slots)
- Right click > Save Playlist As... (available for slots that contain playlists, defaults to "<playlistName>_copy.csv")
- Right click > Print Playlist... (available for slots that contain playlists)

Save is not needed, because playlists are auto-saved now.

Text edit playlist, reload, and remove are all implemented previously.

![image](https://github.com/mpogue2/SquareDesk/assets/6316003/9c63b564-4c62-4954-b24e-fca2d213ae5e)

**Comment by mpogue2** [comment]
I think the top-level Playlist menu is now essentially obsolete.  It works correctly only with Light Mode, where the playlist was in the songTable (no longer true in Dark Mode).

Playlist > Next Song, Playlist > Previous Song, and Playlist > Continuous Play are all broken now.  They work in Light Mode, but not Dark Mode.  All 3 need to be made Playlist-relative, I think.  I'll open a new Issue for that.
