### ISSUE TITLE
Bug: title list: the recent and the age column are not displayed in the title list. 

### ISSUE THREAD

**Issue by Gero5** [mpogue2/SquareDesk#965]
all fields are empty although the title is in the headline 
bug or feature?

**Comment by mpogue2** [comment]
That's probably a bug... they show up in V0.9.5

**Comment by mpogue2** [comment]
OK, there were a number of bugs here, that are fixed by:  bb4e49cb495094ba9b693b1fc237a1d7f398b67f

- **DarkSongTable bug**: the Ages column, which is not resizable, was too small for more than 2 digits of age.  Since I don't use Recent, my recent fence was set to 2018, and I had a lot of songs with 3-digit Ages.  Made the Ages column bigger.
- **DarkMode bug:** reloadSongAges, which has primary responsibility for display Age and Recent, didn't know about the darkSongTable.  It now knows to actually populate the darkSongTable when in Dark Mode.
- **Longstanding bug?**: at startup time, getSongAge is called for every row in the songTable, to initialize Age and Recent.  GetSongAge does up to two SQL queries to find an age (I'm not sure why), BUT it never actually finds anything (ever), and always returns an empty string.  That's a bug, I think.  BUT, that is compensated for by reloadSongAges, which comes in and does one DIFFERENT SQL query, that actually works, and uses that data to overwrite all the Ages and Recents in the songTable.  So, the results of getSongAge are both always wrong and always ignored.  I changed `getSongAge()` to not do the SQL queries at all, and to just return "999" (just in case this pops up in the future, this will be a flag so we know what it is...)
- **Nit bug that probably doesn't matter**: the default "not recent" date for the recent fence was 2018.01.01. Changed to 2023.01.01, although I don't think this matters much, since if user is first installing, they will never have any song plays before the first date of installation.  If a user is actually using recent, they can reset it with Session > Clear Recent at any time, at which point the default will be 2023.01.01 .

After fixing these, Age and Recent show up, and they look like reasonable values.

@danlyke Could you take a look at `getSongAge()` when you get a chance, and tell me that what I did (described above) actually makes sense?  Thanks!
